//! The Bible in the chain (`docs/BIBLE.md`): the American King James
//! Version, as a consensus constant.
//!
//! The text is the pinned file `data/akjv.txt.gz` (provenance, hashes and
//! license in `data/AKJV.md`), **embedded in the binary**: nothing to
//! install or configure. Consensus uses its compressed bytes exactly as
//! shipped, never re-compressed, cut into `BLOCKS` blocks of `BLOCK_LEN`
//! bytes (the last zero-padded) -- gzip makes them close to random, so
//! none can be predicted rather than stored.
//!
//! The blocks are committed by a Poseidon2 Merkle tree of `DEPTH` levels
//! -- every one of its 2^16 positions filled, position `i` holding block
//! `i mod BLOCKS` (so any 16-bit index names a block, with no range check
//! in a circuit) -- whose root is the constant `TEXT_ROOT`; `check`
//! confirms the embedded file against it.
//! A block becomes field elements three bytes to an element (one-to-one:
//! 24 bits always fit below the prime), `BLOCK_ELEMENTS` of them, hashed
//! into its leaf in one permutation. Proving a block in a circuit is then
//! its path: `DEPTH` + 1 permutations.

#![allow(dead_code)] // `path`, `verify`, `text_root`: for proof of work and signatures (steps 2-4)

use std::sync::OnceLock;

use crate::poseidon2::{BabyBear, digest_to_bytes, hash_octets, perm24};

type Octet = [BabyBear; 8];

/// The text: AKJV, gzip -9 -n (`data/AKJV.md`).
pub const TEXT: &[u8] = include_bytes!("../../data/akjv.txt.gz");
/// Bytes per block.
pub const BLOCK_LEN: usize = 32;
/// How many blocks the text makes.
pub const BLOCKS: usize = TEXT.len().div_ceil(BLOCK_LEN);
/// The text tree's depth: 2^16 positions, enough for every block.
pub const DEPTH: usize = 16;
/// A block's field elements: 32 bytes, three to an element.
pub const BLOCK_ELEMENTS: usize = BLOCK_LEN.div_ceil(3);

const _: () = assert!(BLOCKS <= 1 << DEPTH);

pub(crate) const DOMAIN_TEXT_LEAF: u32 = 0x400;
/// Plus the level (0..DEPTH).
pub(crate) const DOMAIN_TEXT_NODE: u32 = 0x500;

/// The text tree's root: a consensus constant (regenerated by the
/// `text_root` test if the pinned file ever changed -- it mustn't).
pub const TEXT_ROOT: &str = "9f8987500179342b1e0464653de69c3227cc4b52bb224d21c388fe3a64c9b65c";

/// Block `i`'s bytes (zero-padded past the end of the text).
pub fn block(i: usize) -> [u8; BLOCK_LEN] {
    let mut out = [0u8; BLOCK_LEN];
    let start = (i * BLOCK_LEN).min(TEXT.len());
    let end = (start + BLOCK_LEN).min(TEXT.len());
    out[..end - start].copy_from_slice(&TEXT[start..end]);
    out
}

/// Block `i` as field elements: three bytes to an element, little-endian.
pub fn block_elements(i: usize) -> [BabyBear; BLOCK_ELEMENTS] {
    let bytes = block(i);
    std::array::from_fn(|e| {
        let chunk = &bytes[3 * e..(3 * e + 3).min(BLOCK_LEN)];
        BabyBear::new(chunk.iter().rev().fold(0u32, |acc, &b| (acc << 8) | b as u32))
    })
}

/// A block's leaf: one permutation.
pub fn leaf(elements: &[BabyBear; BLOCK_ELEMENTS]) -> Octet {
    hash_octets(DOMAIN_TEXT_LEAF, BLOCK_LEN, elements)
}

/// The node above `left` and `right` at `level` (0: just above leaves).
pub fn node(level: usize, left: &Octet, right: &Octet) -> Octet {
    let mut state = [BabyBear::ZERO; 24];
    state[..8].copy_from_slice(left);
    state[8..16].copy_from_slice(right);
    state[16] = BabyBear::new(DOMAIN_TEXT_NODE + level as u32);
    state[17] = BabyBear::new(16);
    perm24().permute(state)[..8].try_into().unwrap()
}

/// The whole text tree, built once: every level, leaves first.
pub struct TextTree {
    levels: Vec<Vec<Octet>>,
}

impl TextTree {
    fn build() -> TextTree {
        let leaves: Vec<Octet> = (0..BLOCKS).map(|i| leaf(&block_elements(i))).collect();
        let mut level: Vec<Octet> = (0..1usize << DEPTH).map(|i| leaves[i % BLOCKS]).collect();
        let mut levels = Vec::with_capacity(DEPTH + 1);
        for h in 0..DEPTH {
            let next = level.chunks_exact(2).map(|pair| node(h, &pair[0], &pair[1])).collect();
            levels.push(std::mem::replace(&mut level, next));
        }
        levels.push(level);
        TextTree { levels }
    }

    pub fn root(&self) -> Octet {
        self.levels[DEPTH][0]
    }

    /// The siblings on block `i`'s path up, bottom first.
    pub fn path(&self, i: usize) -> Vec<Octet> {
        (0..DEPTH).map(|h| self.levels[h][(i >> h) ^ 1]).collect()
    }
}

/// The text tree (built on first use: ~130,000 permutations).
pub fn tree() -> &'static TextTree {
    static TREE: OnceLock<TextTree> = OnceLock::new();
    TREE.get_or_init(TextTree::build)
}

/// Whether `elements` are the block at position `i` of the text tree, by
/// `path`, under `root`.
pub fn verify(root: &Octet, i: usize, elements: &[BabyBear; BLOCK_ELEMENTS], path: &[Octet]) -> bool {
    if i >= 1 << DEPTH || path.len() != DEPTH {
        return false;
    }
    let mut hash = leaf(elements);
    for (h, sibling) in path.iter().enumerate() {
        hash = if (i >> h) & 1 == 0 { node(h, &hash, sibling) } else { node(h, sibling, &hash) };
    }
    hash == *root
}

/// `TEXT_ROOT` as an octet (for the circuits that prove blocks).
pub fn text_root() -> Octet {
    crate::poseidon2::digest_from_bytes(&crate::from_hex32(TEXT_ROOT))
}

/// Whether the embedded text is the pinned one -- checked at startup.
pub fn check() -> bool {
    digest_to_bytes(tree().root()) == crate::from_hex32(TEXT_ROOT)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The pinned file, its blocks, and `TEXT_ROOT`: prints the root, and
    /// fails if the constant is stale.
    #[test]
    fn text_root() {
        assert_eq!(TEXT.len(), 1_291_059);
        assert_eq!(BLOCKS, 40_346);
        assert_eq!(&TEXT[..3], &[0x1f, 0x8b, 0x08], "a gzip file");
        let root = crate::hex(&digest_to_bytes(tree().root()));
        println!("TEXT_ROOT = {root}");
        assert_eq!(root, TEXT_ROOT, "TEXT_ROOT is stale: update it to the above");
        assert!(check());
    }

    /// Blocks encode one-to-one; paths verify, and nothing else does.
    #[test]
    fn blocks_prove_by_path() {
        let t = tree();
        let root = t.root();
        for i in [0, 1, 12_345, BLOCKS - 1] {
            let e = block_elements(i);
            assert!(verify(&root, i, &e, &t.path(i)));
            // Another position, or another block's contents, fails.
            assert!(!verify(&root, i ^ 1, &e, &t.path(i)));
            let mut other = e;
            other[3] = other[3] + BabyBear::ONE;
            assert!(!verify(&root, i, &other, &t.path(i)));
        }
        // The last block is zero-padded; the encoding keeps every byte.
        let last = block(BLOCKS - 1);
        assert_eq!(&last[..TEXT.len() % BLOCK_LEN], &TEXT[TEXT.len() - TEXT.len() % BLOCK_LEN..]);
        assert!(last[TEXT.len() % BLOCK_LEN..].iter().all(|&b| b == 0));
        let e = block_elements(7);
        let mut back = Vec::new();
        for x in e {
            back.extend_from_slice(&x.value().to_le_bytes()[..3]);
        }
        assert_eq!(&back[..BLOCK_LEN], &block(7));
    }
}
