//! FRI (Fast Reed-Solomon IOP of Proximity): the protocol that lets a
//! prover convince a verifier that a function, given only as evaluations
//! over a domain, is close to a polynomial of some bounded degree --
//! without ever revealing the polynomial's coefficients. It works by
//! repeatedly "folding" the evaluations in half (halving the domain size
//! and the degree bound each round) until a tiny base case is reached,
//! with random spot-checks along the way to catch a prover who folded
//! dishonestly.
//!
//! This module, for now: the evaluation domain, and the folding operation
//! itself -- the mathematical core everything else (commitments via
//! `merkle`, the query phase, Fiat-Shamir) builds on top of. Getting
//! folding exactly right matters more than anything else here, since every
//! later piece assumes it's correct; see
//! `fold_matches_direct_polynomial_evaluation` below for why it's trusted.

#![allow(dead_code)]

use crate::poseidon2::BabyBear;

/// `TWO_ADIC_GENERATORS[k]` is a generator of BabyBear's multiplicative
/// subgroup of order `2^k`, for `k = 0..=27` -- BabyBear's prime has
/// 2-adicity 27 (`p - 1 = 2^27 * 15`), the largest power-of-two-order
/// subgroup available, which is what makes repeated halving possible at
/// all. Ported directly from Plonky3's `baby-bear/src/baby_bear.rs`
/// (`TwoAdicData::TWO_ADIC_GENERATORS`), and independently verified rather
/// than trusted blindly: every entry checked (outside this codebase, via a
/// plain modular-exponentiation script) to have *exactly* its claimed
/// order, not merely to divide it, and to equal `generators[27]^(2^(27-k))`.
const TWO_ADIC_GENERATORS: [u32; MAX_TWO_ADICITY + 1] = [
    1, 2013265920, 1728404513, 1592366214, 196396260, 760005850, 1721589904, 397765732, 1732600167,
    1753498361, 341742893, 1340477990, 1282623253, 298008106, 1657000625, 2009781145, 1421947380,
    1286330022, 1559589183, 1049899240, 195061667, 414040701, 570250684, 1267047229, 1003846038,
    1149491290, 975630072, 440564289,
];

pub const MAX_TWO_ADICITY: usize = 27;

/// A generator of BabyBear's order-`2^log_size` multiplicative subgroup --
/// the domain FRI's folding halves repeatedly.
pub fn domain_generator(log_size: usize) -> BabyBear {
    assert!(
        log_size <= MAX_TWO_ADICITY,
        "log_size {log_size} exceeds BabyBear's 2-adicity ({MAX_TWO_ADICITY})"
    );
    BabyBear::new(TWO_ADIC_GENERATORS[log_size])
}

/// The full domain `[g^0, g^1, ..., g^(n-1)]` for `n = 2^log_size`, `g`
/// the order-`n` generator. Point `i + n/2` is always `-`(point `i`),
/// since `g^(n/2)` has order 2 and is therefore `-1` -- the property
/// `fold` relies on to pair up points.
pub fn domain(log_size: usize) -> Vec<BabyBear> {
    let g = domain_generator(log_size);
    let n = 1usize << log_size;
    let mut points = Vec::with_capacity(n);
    let mut cur = BabyBear::ONE;
    for _ in 0..n {
        points.push(cur);
        cur = cur * g;
    }
    points
}

/// One FRI folding step: given evaluations of a polynomial `f` of degree
/// `< domain.len()` over `domain`, and a `challenge`, return evaluations
/// of `f'(y) = f_even(y) + challenge * f_odd(y)` over the squared
/// (half-size) domain, where `f(x) = f_even(x^2) + x * f_odd(x^2)`.
///
/// For each pair `{x, -x}` (`domain[i]` and `domain[i + n/2]`):
/// `f_even(x^2) = (f(x)+f(-x))/2` and `f_odd(x^2) = (f(x)-f(-x))/(2x)`.
/// That's what lets this work from evaluations alone -- no coefficients,
/// no interpolation, just arithmetic on the values already in hand.
pub fn fold(evals: &[BabyBear], domain: &[BabyBear], challenge: BabyBear) -> Vec<BabyBear> {
    assert_eq!(
        evals.len(),
        domain.len(),
        "evaluations and domain must have the same length"
    );
    let n = evals.len();
    assert!(
        n.is_power_of_two() && n > 1,
        "domain size must be a power of two greater than 1, got {n}"
    );
    let half = n / 2;

    let inv2 = BabyBear::new(2).inverse();
    let c = challenge * inv2;

    (0..half)
        .map(|i| {
            let f_x = evals[i];
            let f_neg_x = evals[i + half];
            let x_inv = domain[i].inverse();
            let sum = f_x + f_neg_x;
            let diff = f_x.sub(f_neg_x);
            sum * inv2 + c * (x_inv * diff)
        })
        .collect()
}

/// The domain `fold`'s output lives over: squaring every point in the
/// first half of `domain` (the second half squares to the exact same
/// values, since `domain[i + half] = -domain[i]` and squaring erases the
/// sign) gives the order-`n/2` domain generated by `g^2`.
pub fn fold_domain(domain: &[BabyBear]) -> Vec<BabyBear> {
    let half = domain.len() / 2;
    domain[..half].iter().map(|&x| x * x).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(x: u32) -> BabyBear {
        BabyBear::new(x)
    }

    /// Plain polynomial evaluation from coefficients (Horner's method),
    /// used only as an independent reference for the tests below -- never
    /// called by `fold` itself, which only ever works from evaluations.
    fn eval_poly(coeffs: &[BabyBear], x: BabyBear) -> BabyBear {
        let mut result = BabyBear::ZERO;
        for &c in coeffs.iter().rev() {
            result = result * x + c;
        }
        result
    }

    #[test]
    fn domain_has_the_right_size_and_order() {
        for log_size in 0..=10 {
            let d = domain(log_size);
            assert_eq!(d.len(), 1 << log_size);
            let g = domain_generator(log_size);
            assert_eq!(g.pow(1u64 << log_size), BabyBear::ONE);
            if log_size > 0 {
                assert_ne!(g.pow(1u64 << (log_size - 1)), BabyBear::ONE);
            }
        }
    }

    #[test]
    fn domain_points_pair_up_as_x_and_negative_x() {
        let d = domain(4); // size 16
        let half = d.len() / 2;
        for i in 0..half {
            assert_eq!(d[i + half], d[i].neg());
        }
    }

    /// The test that actually matters: folding evaluations must be
    /// equivalent to folding the underlying polynomial's even/odd
    /// coefficient split, checked directly rather than just trusting
    /// `fold`'s own internal consistency.
    #[test]
    fn fold_matches_direct_polynomial_evaluation() {
        for log_size in [2usize, 3, 4, 6] {
            let n = 1usize << log_size;
            let domain_pts = domain(log_size);
            // A full-degree polynomial: n arbitrary, non-trivial coefficients.
            let coeffs: Vec<BabyBear> = (1..=n as u32).map(v).collect();
            let evals: Vec<BabyBear> = domain_pts.iter().map(|&x| eval_poly(&coeffs, x)).collect();

            let challenge = v(1234567);
            let folded_evals = fold(&evals, &domain_pts, challenge);
            let new_domain = fold_domain(&domain_pts);

            let even_coeffs: Vec<BabyBear> = coeffs.iter().step_by(2).copied().collect();
            let odd_coeffs: Vec<BabyBear> = coeffs.iter().skip(1).step_by(2).copied().collect();
            let expected: Vec<BabyBear> = new_domain
                .iter()
                .map(|&y| eval_poly(&even_coeffs, y) + challenge * eval_poly(&odd_coeffs, y))
                .collect();

            assert_eq!(folded_evals, expected, "mismatch at log_size={log_size}");
        }
    }

    /// Repeated folding, all the way down to a single value, checked at
    /// every step against the same direct reference -- not just the first
    /// round.
    #[test]
    fn repeated_folding_matches_reference_at_every_step() {
        let log_size = 5; // size 32
        let n = 1usize << log_size;
        let mut domain_pts = domain(log_size);
        let mut coeffs: Vec<BabyBear> = (1..=n as u32).map(v).collect();
        let mut evals: Vec<BabyBear> = domain_pts.iter().map(|&x| eval_poly(&coeffs, x)).collect();

        for round in 0..log_size {
            let challenge = v(100 + round as u32);
            let folded = fold(&evals, &domain_pts, challenge);
            let new_domain = fold_domain(&domain_pts);

            let even: Vec<BabyBear> = coeffs.iter().step_by(2).copied().collect();
            let odd: Vec<BabyBear> = coeffs.iter().skip(1).step_by(2).copied().collect();
            let expected: Vec<BabyBear> = new_domain
                .iter()
                .map(|&y| eval_poly(&even, y) + challenge * eval_poly(&odd, y))
                .collect();
            assert_eq!(folded, expected, "mismatch at round {round}");

            // The folded polynomial's own coefficients, for the next round's
            // reference computation.
            coeffs = even
                .iter()
                .zip(odd.iter())
                .map(|(&e, &o)| e + challenge * o)
                .collect();
            evals = folded;
            domain_pts = new_domain;
        }

        // After log_size rounds we're down to one point and one
        // (constant) coefficient.
        assert_eq!(evals.len(), 1);
        assert_eq!(coeffs.len(), 1);
        assert_eq!(evals[0], coeffs[0]);
    }

    #[test]
    #[should_panic]
    fn fold_rejects_mismatched_lengths() {
        let d = domain(3);
        let evals = vec![BabyBear::ZERO; 4];
        fold(&evals, &d, v(1));
    }

    #[test]
    #[should_panic]
    fn fold_rejects_size_one_domain() {
        let d = domain(0);
        let evals = vec![BabyBear::ZERO; 1];
        fold(&evals, &d, v(1));
    }
}
