//! Poseidon2 over the BabyBear field, generic over state width.
//!
//! Three widths are implemented: t=16 (the standard/default BabyBear
//! instantiation used by Plonky3 and SP1), and t=24 / t=32 (wider sponge
//! configurations Plonky3 also publishes). t=4 is *not* a published
//! configuration for this field.
//!
//! All constants below -- external/internal round constants, the internal
//! diagonal, and the 4x4 MDS matrix used by the external linear layer -- are
//! copied from Plonky3's `baby-bear/src/poseidon2.rs`
//! (https://github.com/Plonky3/Plonky3), itself generated by the official
//! Grain-LFSR constant generator per the Poseidon2 paper
//! (https://eprint.iacr.org/2023/323).
//!
//! Correctness for all three widths is checked against Plonky3's own
//! known-answer test vectors in the `tests` module below.
//!
//! `main.rs` doesn't currently call into this module's public API (it just
//! prints "Hello world!"), so allow dead code here rather than suppressing
//! warnings piecemeal -- this module exists to be exercised by its tests.
#![allow(dead_code)]

/// The BabyBear prime: 2^31 - 2^27 + 1.
pub const P: u32 = 2_013_265_921;

const HALF_FULL_ROUNDS: usize = 4; // R_F = 8 total (4 initial + 4 final), same for every width here.

/// An element of the BabyBear field, always kept reduced into [0, P).
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
pub struct BabyBear(u32);

impl BabyBear {
    pub const ZERO: BabyBear = BabyBear(0);
    pub const ONE: BabyBear = BabyBear(1);

    pub fn new(x: u32) -> Self {
        BabyBear(x % P)
    }

    /// `new`, usable in a `const`.
    pub const fn new_const(x: u32) -> Self {
        BabyBear(x % P)
    }

    pub fn value(self) -> u32 {
        self.0
    }

    /// Little-endian byte encoding, for serializing a field element into a
    /// wire format.
    pub fn to_bytes(self) -> [u8; 4] {
        self.0.to_le_bytes()
    }

    pub fn from_bytes(bytes: [u8; 4]) -> Self {
        BabyBear::new(u32::from_le_bytes(bytes))
    }

    pub fn neg(self) -> Self {
        if self.0 == 0 {
            self
        } else {
            BabyBear(P - self.0)
        }
    }

    pub fn add(self, rhs: Self) -> Self {
        let sum = self.0 + rhs.0;
        BabyBear(if sum >= P { sum - P } else { sum })
    }

    pub fn sub(self, rhs: Self) -> Self {
        self.add(rhs.neg())
    }

    pub fn mul(self, rhs: Self) -> Self {
        BabyBear(((self.0 as u64 * rhs.0 as u64) % P as u64) as u32)
    }

    pub fn double(self) -> Self {
        self.add(self)
    }

    /// Exponentiation by repeated squaring.
    pub fn pow(self, mut exp: u64) -> Self {
        let mut base = self;
        let mut acc = BabyBear::ONE;
        while exp > 0 {
            if exp & 1 == 1 {
                acc = acc.mul(base);
            }
            base = base.mul(base);
            exp >>= 1;
        }
        acc
    }

    /// Multiplicative inverse via Fermat's little theorem (a^(P-2) = a^-1).
    pub fn inverse(self) -> Self {
        self.pow((P - 2) as u64)
    }

    /// The Poseidon2 S-box for BabyBear: x -> x^7. (gcd(7, P-1) = 1, so this is
    /// a bijection; degree 3 and 5 are *not* valid here since both divide P-1.)
    fn sbox(self) -> Self {
        let x2 = self.mul(self);
        let x4 = x2.mul(x2);
        x4.mul(x2).mul(self)
    }
}

impl std::ops::Add for BabyBear {
    type Output = BabyBear;
    fn add(self, rhs: Self) -> Self {
        BabyBear::add(self, rhs)
    }
}

impl std::ops::Mul for BabyBear {
    type Output = BabyBear;
    fn mul(self, rhs: Self) -> Self {
        BabyBear::mul(self, rhs)
    }
}

impl std::ops::Sub for BabyBear {
    type Output = BabyBear;
    fn sub(self, rhs: Self) -> Self {
        BabyBear::sub(self, rhs)
    }
}

impl std::ops::Neg for BabyBear {
    type Output = BabyBear;
    fn neg(self) -> Self {
        BabyBear::neg(self)
    }
}

/// 1 / 2^k, computed via the field inverse rather than a pasted constant.
fn inv_two_pow(k: u32) -> BabyBear {
    BabyBear::new(1 << k).inverse()
}

// --- Round constants, verbatim from Plonky3's baby-bear/src/poseidon2.rs ---

const EXTERNAL_RC_INITIAL_16: [[u32; 16]; HALF_FULL_ROUNDS] = [
    [
        1774958255, 1185780729, 1621102414, 1796380621, 588815102, 1932426223, 1925334750,
        747903232, 89648862, 360728943, 977184635, 1425273457, 256487465, 1200041953, 572403254,
        448208942,
    ],
    [
        1215789478, 944884184, 953948096, 547326025, 646827752, 889997530, 1536873262, 86189867,
        1065944411, 32019634, 333311454, 456061748, 1963448500, 1827584334, 1391160226, 1348741381,
    ],
    [
        88424255, 104111868, 1763866748, 79691676, 1988915530, 1050669594, 359890076, 573163527,
        222820492, 159256268, 669703072, 763177444, 889367200, 256335831, 704371273, 25886717,
    ],
    [
        51754520, 1833211857, 454499742, 1384520381, 777848065, 1053320300, 1851729162, 344647910,
        401996362, 1046925956, 5351995, 1212119315, 754867989, 36972490, 751272725, 506915399,
    ],
];

const EXTERNAL_RC_FINAL_16: [[u32; 16]; HALF_FULL_ROUNDS] = [
    [
        1922082829, 1870549801, 1502529704, 1990744480, 1700391016, 1702593455, 321330495,
        528965731, 183414327, 1886297254, 1178602734, 1923111974, 744004766, 549271463, 1781349648,
        542259047,
    ],
    [
        1536158148, 715456982, 503426110, 340311124, 1558555932, 1226350925, 742828095, 1338992758,
        1641600456, 1843351545, 301835475, 43203215, 386838401, 1520185679, 1235297680, 904680097,
    ],
    [
        1491801617, 1581784677, 913384905, 247083962, 532844013, 107190701, 213827818, 1979521776,
        1358282574, 1681743681, 1867507480, 1530706910, 507181886, 695185447, 1172395131,
        1250800299,
    ],
    [
        1503161625, 817684387, 498481458, 494676004, 1404253825, 108246855, 59414691, 744214112,
        890862029, 1342765939, 1417398904, 1897591937, 1066647396, 1682806907, 1015795079,
        1619482808,
    ],
];

const INTERNAL_RC_16: [u32; 13] = [
    1518359488, 1765533241, 945325693, 422793067, 311365592, 1311448267, 1629555936, 1009879353,
    190525218, 786108885, 557776863, 212616710, 605745517,
];

const EXTERNAL_RC_INITIAL_24: [[u32; 24]; HALF_FULL_ROUNDS] = [
    [
        262278199, 127253399, 314968988, 246143118, 157582794, 118043943, 454905424, 815798990,
        1004040026, 1773108264, 1066694495, 1930780904, 1180307149, 1464793095, 1660766320,
        1389166148, 343354132, 1307439985, 638242172, 525458520, 1964135730, 1751797115,
        1421525369, 831813382,
    ],
    [
        695835963, 1845603984, 540703332, 1333667262, 1917861751, 1170029417, 1989924532,
        1518763784, 1339793538, 622609176, 686842369, 1737016378, 1282239129, 897025192, 716894289,
        1997503974, 395622276, 1201063290, 1917549072, 1150912935, 1687379185, 1507936940,
        241306552, 989176635,
    ],
    [
        1147522062, 27129487, 1257820264, 142102402, 217046702, 1664590951, 855276054, 1215259350,
        946500736, 552696906, 1424297384, 538103555, 1608853840, 162510541, 623051854, 1549062383,
        1908416316, 1622328571, 1079030649, 1584033957, 1099252725, 1910423126, 447555988,
        862495875,
    ],
    [
        128479034, 1587822577, 608401422, 1290028279, 342857858, 825405577, 427731030, 1718628547,
        588764636, 204228775, 1454563174, 1740472809, 1338899225, 1269493554, 53007114, 1647670797,
        306391314, 172614232, 51256176, 1221257987, 1239734761, 273790406, 1781980094, 1291790245,
    ],
];

const EXTERNAL_RC_FINAL_24: [[u32; 24]; HALF_FULL_ROUNDS] = [
    [
        53041581, 723038058, 1439947916, 1136469704, 205609311, 1883820770, 14387587, 720724951,
        1854174607, 1629316321, 530151394, 1679178250, 1549779579, 48375137, 976057819, 463976218,
        875839332, 1946596189, 434078361, 1878280202, 1363837384, 1470845646, 1792450386,
        1040977421,
    ],
    [
        1209164052, 714957516, 390340387, 1213686459, 790726260, 117294666, 140621810, 993455846,
        1889603648, 78845751, 925018226, 708123747, 1647665372, 1649953458, 942439428, 1006235079,
        238616145, 930036496, 1401020792, 989618631, 1545325389, 1715719711, 755691969, 150307788,
    ],
    [
        1567618575, 1663353317, 1950429111, 1891637550, 192082241, 1080533265, 1463323727,
        890243564, 158646617, 1402624179, 59510015, 1198261138, 1065075039, 1150410028, 1293938517,
        76770019, 1478577620, 1748789933, 457372011, 1841795381, 760115692, 1042892522, 1507649755,
        1827572010,
    ],
    [
        1206940496, 1896271507, 1003792297, 738091882, 1124078057, 1889898, 813674331, 228520958,
        1832911930, 781141772, 459826664, 202271745, 1296144415, 1111203133, 1090783436, 641665156,
        1393671120, 1303271640, 809508074, 162506101, 1262312258, 1672219447, 1608891156,
        1380248020,
    ],
];

const INTERNAL_RC_24: [u32; 21] = [
    497520322, 1930103076, 1052077299, 1540960371, 924863639, 1365519753, 1726563304, 440300254,
    1891545577, 822033215, 1111544260, 308575117, 1708681573, 1240419708, 1199068823, 1186174623,
    1551596046, 1886977120, 1327682690, 1210751726, 1810596765,
];

const EXTERNAL_RC_INITIAL_32: [[u32; 32]; HALF_FULL_ROUNDS] = [
    [
        1729160065, 27999661, 1237173535, 1103727717, 596139402, 619347324, 1801845869, 1627808090,
        139024371, 360461876, 1303224591, 1826595949, 468846782, 1540501420, 1284230111, 670536848,
        1883853842, 708936782, 1371236849, 840293409, 1729185817, 665479689, 1598897325,
        1607911204, 457969805, 1469698125, 1452024111, 1745363419, 1644640041, 580839296,
        995071171, 396602452,
    ],
    [
        1815642745, 1215757909, 829485578, 862993998, 60295857, 19902714, 341764315, 1233214256,
        1185777564, 1388073021, 1483026647, 1547106789, 42886403, 137429864, 1968465478,
        1931810545, 860372570, 77628460, 439432665, 1400581809, 1538215799, 1266208109, 1525492810,
        1724421089, 1012175782, 1187392508, 1447975194, 1390335911, 13697837, 724621313, 270380023,
        788210125,
    ],
    [
        1245060153, 1240462706, 773049076, 24012697, 459070276, 399125958, 240127712, 21088923,
        664478582, 1715979275, 231403068, 384302329, 1508300380, 515322057, 677410888, 1165131676,
        1314144251, 65938768, 17618251, 47991670, 725260860, 783004377, 110265683, 757314549,
        1839407793, 354937863, 239405946, 1402344978, 552692496, 384830560, 1278858511, 1104518518,
    ],
    [
        1381234722, 995349377, 461326090, 1581091164, 1382383909, 18976979, 1700150144, 487565895,
        896906185, 1275960608, 416280735, 1688722012, 789842725, 329227825, 1726180309, 1682098193,
        1485282254, 1607239622, 1745333772, 1091683927, 1664911657, 1955998065, 1069649592,
        1164767880, 838256850, 1815753128, 1837293392, 1027811219, 1100325527, 1808702357,
        1015163632, 1982457267,
    ],
];

const EXTERNAL_RC_FINAL_32: [[u32; 32]; HALF_FULL_ROUNDS] = [
    [
        2009876055, 956324903, 1221427337, 645725371, 474073733, 1102287935, 552039034, 1689090291,
        333267987, 272819164, 1957554988, 768463815, 100691900, 900073961, 229582652, 978282831,
        1509756957, 668078379, 423081631, 780697788, 1086399529, 108619174, 1856090989, 1845577582,
        701329802, 1409730195, 1373515418, 1843148938, 1400255603, 396516543, 522814157, 432691965,
    ],
    [
        762330259, 203964644, 752517837, 1551847904, 498436102, 1018571729, 725960219, 1644477008,
        1750593724, 1257415528, 851527412, 449830291, 767792496, 230550350, 1354692685, 1870897708,
        1129068353, 543220064, 1760923403, 623489725, 288114536, 1883282658, 458704398, 568099212,
        1600869168, 1145016250, 555389150, 1495091760, 1532640885, 1666986810, 519924336,
        1563771999,
    ],
    [
        1446498082, 1855695025, 280317484, 69803704, 760128835, 1913281633, 442196771, 1759606503,
        638883701, 1492323307, 1157890731, 613581397, 851810645, 727413345, 1652127647, 1503357582,
        1892763091, 931579089, 288765024, 587145601, 1292303440, 665363423, 1685977476, 980716739,
        1252597410, 569037473, 1355636109, 114753478, 1539641623, 1173899452, 314824177,
        1216319589,
    ],
    [
        370615356, 1552381156, 1992086508, 882674251, 643656246, 972842286, 610808232, 1216370940,
        173831638, 1980583661, 757684141, 1636349694, 545572213, 1741029216, 1030588827, 660162122,
        507714002, 167704630, 810967268, 607642520, 1770949549, 1369555082, 1869300458, 1316643372,
        861517941, 1875492637, 882822549, 1076559853, 243081034, 1969815445, 1831269979,
        1383829493,
    ],
];

const INTERNAL_RC_32: [u32; 30] = [
    1037946958, 1513948504, 1983802485, 1735335304, 2008556117, 635406929, 1769749264, 63925983,
    313872248, 1714672948, 1114619063, 1430676956, 1451867570, 317147102, 1623361349, 298470309,
    1057985923, 1455937939, 553027423, 1776654280, 1016141171, 700970754, 442032405, 688992664,
    2003511455, 512896738, 560331760, 684502904, 428025981, 1227563744,
];

/// Internal-layer diagonal for width 16: M_I = J + diag(V) (J = all-ones
/// matrix). Expressed via field inverses rather than pasted decimal
/// constants, so the arithmetic is checkable by inspection, and transcribed
/// directly from Plonky3's `InternalLayerBaseParameters<_, 16>::internal_layer_mat_mul`.
fn diagonal_16() -> [BabyBear; 16] {
    let (two, three, four) = (BabyBear::new(2), BabyBear::new(3), BabyBear::new(4));
    let inv2 = two.inverse();
    [
        two.neg(),
        BabyBear::ONE,
        two,
        inv2,
        three,
        four,
        inv2.neg(),
        three.neg(),
        four.neg(),
        inv_two_pow(8),
        inv_two_pow(2),
        inv_two_pow(3),
        inv_two_pow(27),
        inv_two_pow(8).neg(),
        inv_two_pow(4).neg(),
        inv_two_pow(27).neg(),
    ]
}

/// Internal-layer diagonal for width 24, transcribed the same way from
/// `InternalLayerBaseParameters<_, 24>::internal_layer_mat_mul`.
fn diagonal_24() -> [BabyBear; 24] {
    let (two, three, four) = (BabyBear::new(2), BabyBear::new(3), BabyBear::new(4));
    let inv2 = two.inverse();
    [
        two.neg(),
        BabyBear::ONE,
        two,
        inv2,
        three,
        four,
        inv2.neg(),
        three.neg(),
        four.neg(),
        inv_two_pow(8),
        inv_two_pow(2),
        inv_two_pow(3),
        inv_two_pow(4),
        inv_two_pow(7),
        inv_two_pow(9),
        inv_two_pow(27),
        inv_two_pow(8).neg(),
        inv_two_pow(2).neg(),
        inv_two_pow(3).neg(),
        inv_two_pow(4).neg(),
        inv_two_pow(5).neg(),
        inv_two_pow(6).neg(),
        inv_two_pow(7).neg(),
        inv_two_pow(27).neg(),
    ]
}

/// Internal-layer diagonal for width 32, transcribed the same way from
/// `InternalLayerBaseParameters<_, 32>::internal_layer_mat_mul`.
fn diagonal_32() -> [BabyBear; 32] {
    let (two, three, four) = (BabyBear::new(2), BabyBear::new(3), BabyBear::new(4));
    let inv2 = two.inverse();
    [
        two.neg(),
        BabyBear::ONE,
        two,
        inv2,
        three,
        four,
        inv2.neg(),
        three.neg(),
        four.neg(),
        inv_two_pow(8),
        inv_two_pow(2),
        inv_two_pow(3),
        inv_two_pow(4),
        inv_two_pow(5),
        inv_two_pow(6),
        inv_two_pow(7),
        inv_two_pow(9),
        inv_two_pow(10),
        inv_two_pow(12),
        inv_two_pow(27),
        inv_two_pow(8).neg(),
        inv_two_pow(2).neg(),
        inv_two_pow(3).neg(),
        inv_two_pow(4).neg(),
        inv_two_pow(5).neg(),
        inv_two_pow(6).neg(),
        inv_two_pow(7).neg(),
        inv_two_pow(9).neg(),
        inv_two_pow(10).neg(),
        inv_two_pow(12).neg(),
        inv_two_pow(14).neg(),
        inv_two_pow(27).neg(),
    ]
}

/// The fastest 4x4 MDS matrix from the Poseidon2 paper (Appendix B), used as
/// the building block of every external linear layer here:
///   [ 2 3 1 1 ]
///   [ 1 2 3 1 ]
///   [ 1 1 2 3 ]
///   [ 3 1 1 2 ]
fn apply_mat4(x: &mut [BabyBear; 4]) {
    let t01 = x[0] + x[1];
    let t23 = x[2] + x[3];
    let t0123 = t01 + t23;
    let t01123 = t0123 + x[1];
    let t01233 = t0123 + x[3];
    x[3] = t01233 + x[0].double();
    x[1] = t01123 + x[2].double();
    x[0] = t01123 + t01;
    x[2] = t01233 + t23;
}

/// The external linear layer: apply the 4x4 MDS matrix to each 4-element
/// chunk of the state, then mix across chunks at each position. Equivalent
/// to multiplying by the `WIDTH x WIDTH` block matrix
/// `[[2M M ... M], [M 2M ... M], ..., [M M ... 2M]]` for the 4x4 matrix M above.
/// Works for any WIDTH that's a multiple of 4.
fn apply_external_layer<const WIDTH: usize>(state: &mut [BabyBear; WIDTH]) {
    for chunk in state.chunks_mut(4) {
        let mut block: [BabyBear; 4] = chunk.try_into().unwrap();
        apply_mat4(&mut block);
        chunk.copy_from_slice(&block);
    }

    let mut sums = [BabyBear::ZERO; 4];
    for k in 0..4 {
        for j in (0..WIDTH).step_by(4) {
            sums[k] = sums[k] + state[j + k];
        }
    }
    for (i, elem) in state.iter_mut().enumerate() {
        *elem = *elem + sums[i % 4];
    }
}

/// The internal (partial-round) linear layer: (J + diag(V)) * state, i.e.
/// out[i] = V[i] * state[i] + sum(state).
fn apply_internal_layer<const WIDTH: usize>(
    state: &mut [BabyBear; WIDTH],
    diag: &[BabyBear; WIDTH],
) {
    let sum = state.iter().fold(BabyBear::ZERO, |a, &b| a + b);
    for i in 0..WIDTH {
        state[i] = state[i] * diag[i] + sum;
    }
}

/// A Poseidon2 permutation over BabyBear at a given state width.
pub struct Poseidon2BabyBear<const WIDTH: usize> {
    // Crate-visible so `poseidon2_air` can lay the very same constants out
    // as a circuit, rather than keeping a second copy that could drift.
    pub(crate) ext_initial: [[BabyBear; WIDTH]; HALF_FULL_ROUNDS],
    pub(crate) ext_final: [[BabyBear; WIDTH]; HALF_FULL_ROUNDS],
    pub(crate) internal_rc: Vec<BabyBear>,
    pub(crate) internal_diag: [BabyBear; WIDTH],
    /// The same constants in Montgomery form, for `permute`.
    mont: MontConstants<WIDTH>,
}

// ---- Montgomery arithmetic, for the permutation's inner loop ---------------
//
// `permute` runs on raw `u32`s in Montgomery form (`x·2^32 mod P`), where a
// product reduces with two multiplications and no division, and sums in the
// linear layers accumulate in `u64` and reduce once. Inputs and outputs are
// converted at the boundary, so nothing outside sees the representation.

/// `P^-1 mod 2^32`.
const MONTY_MU: u32 = {
    // Newton iteration for the inverse mod 2^32.
    let mut inv: u32 = 1;
    let mut i = 0;
    while i < 5 {
        inv = inv.wrapping_mul(2u32.wrapping_sub(P.wrapping_mul(inv)));
        i += 1;
    }
    inv
};

/// `x · 2^-32 mod P`, for `x < P · 2^32`.
#[inline(always)]
pub(crate) fn monty_reduce(x: u64) -> u32 {
    let m = (x as u32).wrapping_mul(MONTY_MU);
    let u = m as u64 * P as u64;
    let (diff, borrow) = x.overflowing_sub(u);
    let hi = (diff >> 32) as u32;
    if borrow { hi.wrapping_add(P) } else { hi }
}

#[inline(always)]
pub(crate) fn monty_mul(a: u32, b: u32) -> u32 {
    monty_reduce(a as u64 * b as u64)
}

#[inline(always)]
pub(crate) fn to_monty(x: BabyBear) -> u32 {
    (((x.0 as u64) << 32) % P as u64) as u32
}

#[inline(always)]
pub(crate) fn from_monty(x: u32) -> BabyBear {
    BabyBear(monty_reduce(x as u64))
}

/// `x mod P` for `x < 2^37`, by folding: `2^31 ≡ 2^27 - 1 (mod P)`, so
/// `hi·2^31 + lo ≡ lo + hi·2^27 - hi`. Shifts and adds only -- unlike `%`
/// on `u64`, it vectorizes.
#[inline(always)]
fn reduce_wide(x: u64) -> u32 {
    const MASK: u64 = (1 << 31) - 1;
    let (hi, lo) = (x >> 31, x & MASK);
    let y = lo + (hi << 27) - hi; // < 2^34
    let (hi, lo) = (y >> 31, y & MASK);
    let z = lo + (hi << 27) - hi; // < 2^31 + 2^30 < 2P
    let z = z as u32;
    if z >= P { z - P } else { z }
}

#[inline(always)]
pub(crate) fn add_mod(a: u32, b: u32) -> u32 {
    let s = a + b;
    if s >= P { s - P } else { s }
}

#[inline(always)]
pub(crate) fn sub_mod(a: u32, b: u32) -> u32 {
    let (d, borrow) = a.overflowing_sub(b);
    if borrow { d.wrapping_add(P) } else { d }
}

#[inline(always)]
fn sbox_monty(x: u32) -> u32 {
    let x2 = monty_mul(x, x);
    let x3 = monty_mul(x2, x);
    let x6 = monty_mul(x3, x3);
    monty_mul(x6, x)
}

/// How many states `permute_lanes` runs in lockstep.
pub const LANES: usize = 8;

#[inline(always)]
fn sbox_lanes(x: &mut [u32; LANES], rc: u32) {
    for v in x.iter_mut() {
        *v = sbox_monty(add_mod(*v, rc));
    }
}

#[inline(always)]
fn external_layer_lanes<const WIDTH: usize>(s: &mut [[u32; LANES]; WIDTH]) {
    let mut wide = [[0u64; LANES]; WIDTH];
    for j in (0..WIDTH).step_by(4) {
        for l in 0..LANES {
            let x = [s[j][l] as u64, s[j + 1][l] as u64, s[j + 2][l] as u64, s[j + 3][l] as u64];
            let t01 = x[0] + x[1];
            let t23 = x[2] + x[3];
            let t0123 = t01 + t23;
            let t01123 = t0123 + x[1];
            let t01233 = t0123 + x[3];
            wide[j + 3][l] = t01233 + 2 * x[0];
            wide[j + 1][l] = t01123 + 2 * x[2];
            wide[j][l] = t01123 + t01;
            wide[j + 2][l] = t01233 + t23;
        }
    }
    let mut sums = [[0u64; LANES]; 4];
    for j in 0..WIDTH {
        for l in 0..LANES {
            sums[j % 4][l] += wide[j][l];
        }
    }
    for j in 0..WIDTH {
        for l in 0..LANES {
            s[j][l] = reduce_wide(wide[j][l] + sums[j % 4][l]);
        }
    }
}

struct MontConstants<const WIDTH: usize> {
    ext_initial: [[u32; WIDTH]; HALF_FULL_ROUNDS],
    ext_final: [[u32; WIDTH]; HALF_FULL_ROUNDS],
    internal_rc: Vec<u32>,
    internal_diag: [u32; WIDTH],
}

/// The external linear layer on reduced values: each 4-chunk through the
/// 4x4 matrix (entries summing to 7 per row), plus the per-position sums
/// across chunks -- at most 49·P before the one reduction per element.
#[inline(always)]
fn external_layer_monty<const WIDTH: usize>(s: &mut [u32; WIDTH]) {
    let mut wide = [0u64; WIDTH];
    for (chunk, out) in s.chunks(4).zip(wide.chunks_mut(4)) {
        let x = [chunk[0] as u64, chunk[1] as u64, chunk[2] as u64, chunk[3] as u64];
        let t01 = x[0] + x[1];
        let t23 = x[2] + x[3];
        let t0123 = t01 + t23;
        let t01123 = t0123 + x[1];
        let t01233 = t0123 + x[3];
        out[3] = t01233 + 2 * x[0];
        out[1] = t01123 + 2 * x[2];
        out[0] = t01123 + t01;
        out[2] = t01233 + t23;
    }
    let mut sums = [0u64; 4];
    for chunk in wide.chunks(4) {
        for k in 0..4 {
            sums[k] += chunk[k];
        }
    }
    for (i, (slot, w)) in s.iter_mut().zip(wide).enumerate() {
        *slot = reduce_wide(w + sums[i % 4]);
    }
}

impl<const WIDTH: usize> Poseidon2BabyBear<WIDTH> {
    fn assemble(
        ext_initial: [[BabyBear; WIDTH]; HALF_FULL_ROUNDS],
        ext_final: [[BabyBear; WIDTH]; HALF_FULL_ROUNDS],
        internal_rc: Vec<BabyBear>,
        internal_diag: [BabyBear; WIDTH],
    ) -> Self {
        let mont = MontConstants {
            ext_initial: ext_initial.map(|r| r.map(to_monty)),
            ext_final: ext_final.map(|r| r.map(to_monty)),
            internal_rc: internal_rc.iter().map(|&c| to_monty(c)).collect(),
            internal_diag: internal_diag.map(to_monty),
        };
        Poseidon2BabyBear {
            ext_initial,
            ext_final,
            internal_rc,
            internal_diag,
            mont,
        }
    }
}

impl<const WIDTH: usize> Poseidon2BabyBear<WIDTH> {
    /// The full Poseidon2 permutation: an initial external linear layer, then
    /// R_F/2 full rounds, R_P partial rounds, and R_F/2 more full rounds.
    pub fn permute(&self, input: [BabyBear; WIDTH]) -> [BabyBear; WIDTH] {
        let c = &self.mont;
        let mut s = input.map(to_monty);
        external_layer_monty(&mut s);
        for round in &c.ext_initial {
            for i in 0..WIDTH {
                s[i] = sbox_monty(add_mod(s[i], round[i]));
            }
            external_layer_monty(&mut s);
        }
        for &rc in &c.internal_rc {
            s[0] = sbox_monty(add_mod(s[0], rc));
            let sum = reduce_wide(s.iter().map(|&x| x as u64).sum::<u64>());
            for (x, &d) in s.iter_mut().zip(&c.internal_diag) {
                *x = add_mod(monty_mul(*x, d), sum);
            }
        }
        for round in &c.ext_final {
            for i in 0..WIDTH {
                s[i] = sbox_monty(add_mod(s[i], round[i]));
            }
            external_layer_monty(&mut s);
        }
        s.map(from_monty)
    }

    /// `permute` on `LANES` states at once, in lockstep: every step runs
    /// across all of them, written as plain loops over the lanes so the
    /// compiler can keep them in vector registers (and the CPU overlaps
    /// them even where it doesn't). For hashing many independent inputs --
    /// Merkle leaves and nodes.
    pub fn permute_lanes(&self, input: &[[BabyBear; WIDTH]; LANES]) -> [[BabyBear; WIDTH]; LANES] {
        #[cfg(target_arch = "x86_64")]
        if std::arch::is_x86_feature_detected!("avx2") {
            // SAFETY: the CPU supports AVX2, checked just above.
            return unsafe { self.permute_lanes_avx2(input) };
        }
        self.permute_lanes_generic(input)
    }

    /// `permute_lanes_generic` compiled with AVX2 enabled, so the lane
    /// loops become vector instructions.
    #[cfg(target_arch = "x86_64")]
    #[target_feature(enable = "avx2")]
    unsafe fn permute_lanes_avx2(&self, input: &[[BabyBear; WIDTH]; LANES]) -> [[BabyBear; WIDTH]; LANES] {
        self.permute_lanes_generic(input)
    }

    #[inline(always)]
    fn permute_lanes_generic(&self, input: &[[BabyBear; WIDTH]; LANES]) -> [[BabyBear; WIDTH]; LANES] {
        let c = &self.mont;
        // s[i][l]: element i of lane l's state.
        let mut s = [[0u32; LANES]; WIDTH];
        for (l, state) in input.iter().enumerate() {
            for i in 0..WIDTH {
                s[i][l] = to_monty(state[i]);
            }
        }
        external_layer_lanes(&mut s);
        for round in &c.ext_initial {
            for i in 0..WIDTH {
                sbox_lanes(&mut s[i], round[i]);
            }
            external_layer_lanes(&mut s);
        }
        for &rc in &c.internal_rc {
            sbox_lanes(&mut s[0], rc);
            let mut sum = [0u64; LANES];
            for row in &s {
                for l in 0..LANES {
                    sum[l] += row[l] as u64;
                }
            }
            let sum = sum.map(reduce_wide);
            for (row, &d) in s.iter_mut().zip(&c.internal_diag) {
                for (x, &t) in row.iter_mut().zip(&sum) {
                    *x = add_mod(monty_mul(*x, d), t);
                }
            }
        }
        for round in &c.ext_final {
            for i in 0..WIDTH {
                sbox_lanes(&mut s[i], round[i]);
            }
            external_layer_lanes(&mut s);
        }
        let mut out = [[BabyBear::ZERO; WIDTH]; LANES];
        for (l, state) in out.iter_mut().enumerate() {
            for i in 0..WIDTH {
                state[i] = from_monty(s[i][l]);
            }
        }
        out
    }

    /// The textbook permutation on `BabyBear` arithmetic -- what `permute`
    /// must agree with.
    #[cfg(test)]
    fn permute_reference(&self, input: [BabyBear; WIDTH]) -> [BabyBear; WIDTH] {
        let mut s = input;
        apply_external_layer(&mut s);

        for round in &self.ext_initial {
            for i in 0..WIDTH {
                s[i] = (s[i] + round[i]).sbox();
            }
            apply_external_layer(&mut s);
        }

        for &rc in &self.internal_rc {
            s[0] = (s[0] + rc).sbox();
            apply_internal_layer(&mut s, &self.internal_diag);
        }

        for round in &self.ext_final {
            for i in 0..WIDTH {
                s[i] = (s[i] + round[i]).sbox();
            }
            apply_external_layer(&mut s);
        }

        s
    }

    /// A simple sponge on top of the verified permutation: absorb up to
    /// `WIDTH` field elements (zero-padded) with capacity fixed to zero, and
    /// return the first 8 output limbs as the digest. This is a
    /// straightforward construction built on the permutation above, not a
    /// copy of any particular Plonky3 hasher's rate/capacity wiring.
    pub fn hash(&self, inputs: &[BabyBear]) -> [BabyBear; 8] {
        assert!(
            inputs.len() <= WIDTH,
            "input longer than one absorption (width {WIDTH})"
        );
        let mut state = [BabyBear::ZERO; WIDTH];
        state[..inputs.len()].copy_from_slice(inputs);
        let out = self.permute(state);
        out[..8].try_into().unwrap()
    }

    /// `PoseidonCompress_{WIDTH,U}(x) = Truncate_U(permute(x) + x)`: a
    /// Miyaguchi-Preneel-style feed-forward compression function, following
    /// the notation and construction in Drake, "Technical Note: LeanSig for
    /// Post-Quantum Ethereum" (IACR eprint 2025/1332), Section 5. This is the
    /// hash-call shape that scheme uses throughout a Poseidon2-based WOTS
    /// (chain hashing, message hashing, etc.) rather than the bare
    /// permutation or the sponge above.
    pub fn compress<const U: usize>(&self, input: [BabyBear; WIDTH]) -> [BabyBear; U] {
        debug_assert!(U <= WIDTH, "compress output width must fit the state");
        let permuted = self.permute(input);
        let mut out = [BabyBear::ZERO; U];
        for (i, slot) in out.iter_mut().enumerate() {
            *slot = permuted[i] + input[i];
        }
        out
    }
}

impl Poseidon2BabyBear<16> {
    pub fn new() -> Self {
        Self::assemble(
            EXTERNAL_RC_INITIAL_16.map(|r| r.map(BabyBear::new)),
            EXTERNAL_RC_FINAL_16.map(|r| r.map(BabyBear::new)),
            INTERNAL_RC_16.map(BabyBear::new).to_vec(),
            diagonal_16(),
        )
    }
}

impl Poseidon2BabyBear<24> {
    pub fn new() -> Self {
        Self::assemble(
            EXTERNAL_RC_INITIAL_24.map(|r| r.map(BabyBear::new)),
            EXTERNAL_RC_FINAL_24.map(|r| r.map(BabyBear::new)),
            INTERNAL_RC_24.map(BabyBear::new).to_vec(),
            diagonal_24(),
        )
    }
}

impl Poseidon2BabyBear<32> {
    pub fn new() -> Self {
        Self::assemble(
            EXTERNAL_RC_INITIAL_32.map(|r| r.map(BabyBear::new)),
            EXTERNAL_RC_FINAL_32.map(|r| r.map(BabyBear::new)),
            INTERNAL_RC_32.map(BabyBear::new).to_vec(),
            diagonal_32(),
        )
    }
}

impl Default for Poseidon2BabyBear<16> {
    fn default() -> Self {
        Self::new()
    }
}

impl Default for Poseidon2BabyBear<24> {
    fn default() -> Self {
        Self::new()
    }
}

impl Default for Poseidon2BabyBear<32> {
    fn default() -> Self {
        Self::new()
    }
}

/// The width-24 permutation, built once and shared. Building one derives
/// every round constant and the internal diagonal (dozens of field
/// inversions) -- far more work than a permutation itself -- so anything
/// hashing in a loop must use this rather than `new()` per call.
pub fn perm24() -> &'static Poseidon2BabyBear<24> {
    static PERM: std::sync::OnceLock<Poseidon2BabyBear<24>> = std::sync::OnceLock::new();
    PERM.get_or_init(Poseidon2BabyBear::<24>::new)
}

/// `perm24`, for width 16.
pub fn perm16() -> &'static Poseidon2BabyBear<16> {
    static PERM: std::sync::OnceLock<Poseidon2BabyBear<16>> = std::sync::OnceLock::new();
    PERM.get_or_init(Poseidon2BabyBear::<16>::new)
}

/// t = 16 is the standard BabyBear instantiation (Plonky3/SP1's default).
pub type Poseidon2BabyBear16 = Poseidon2BabyBear<16>;

/// Domain tags for `hash_elements` -- one per purpose, so two different
/// kinds of hashed data can never collide even on equal element lists.
pub const DOMAIN_COMMITMENT: u32 = 1;
pub const DOMAIN_SIGNING: u32 = 2;
/// `hash_bytes`.
pub const DOMAIN_BYTES: u32 = 3;
/// A WOTS public key's hash (`wots::PublicKey::hash`).
pub const DOMAIN_PUBKEY: u32 = 4;
/// A Merkle tree leaf (`merkle`).
pub const DOMAIN_MERKLE_LEAF: u32 = 5;
/// A compiled constraint program (`symbolic::Program::digest`).
pub const DOMAIN_PROGRAM: u32 = 6;
/// A verifying key: the hash of a circuit's preprocessed cap.
pub const DOMAIN_VK: u32 = 7;
/// A leaf of an aggregation tree's data: the hash of a proven statement.
pub const DOMAIN_DATA_LEAF: u32 = 8;
/// An internal node of an aggregation tree's data.
pub const DOMAIN_DATA_NODE: u32 = 9;
/// A Merkle tree internal node, plus its level -- one domain per level.
pub const DOMAIN_MERKLE_NODE: u32 = 0x100;

/// Elements absorbed per permutation by `hash_elements`.
pub const SPONGE_RATE: usize = 16;

/// A proper sponge over field elements: width-24 Poseidon2, rate 16,
/// capacity 8. The capacity starts out holding `domain` and the input's
/// length, and input is only ever added into the rate part -- so, unlike
/// `hash_bytes`, a later block can't cancel an earlier one (the capacity
/// is out of an attacker's direct reach), and inputs of different lengths
/// can't collide through padding (the length is part of the initial
/// state). The first 8 elements of the final state are the digest.
///
/// Designed to be cheap to recompute inside a STARK: one permutation per
/// 16 elements, no byte handling.
pub fn hash_elements(domain: u32, elements: &[BabyBear]) -> [BabyBear; 8] {
    sponge(domain, elements.len(), elements)
}

/// `hash_elements`' sponge, with the length recorded in the capacity
/// given explicitly -- `hash_bytes` records its *byte* length, since its
/// last element may hold padding.
fn sponge(domain: u32, length: usize, elements: &[BabyBear]) -> [BabyBear; 8] {
    assert!(length < P as usize, "input too long to encode its length");
    let perm24 = perm24();
    let mut state = [BabyBear::ZERO; 24];
    state[SPONGE_RATE] = BabyBear::new(domain);
    state[SPONGE_RATE + 1] = BabyBear::new(length as u32);
    if elements.is_empty() {
        state = perm24.permute(state);
    }
    for block in elements.chunks(SPONGE_RATE) {
        for (slot, &e) in state.iter_mut().zip(block) {
            *slot = *slot + e;
        }
        state = perm24.permute(state);
    }
    state[..8].try_into().unwrap()
}

/// Hash bytes that encode field elements (4 bytes each, little-endian) --
/// Merkle leaves of trace rows, say -- a quarter fewer elements than
/// `hash_bytes`' general 3-byte packing. Each 4-byte group is reduced mod
/// P, so two byte strings encoding the *same* elements (one with a
/// non-canonical group) hash alike; that's harmless for data only ever
/// read back as those elements. The byte length is recorded, so a short
/// final group is unambiguous.
pub fn hash_words(domain: u32, bytes: &[u8]) -> [BabyBear; 8] {
    let elements: Vec<BabyBear> = bytes
        .chunks(4)
        .map(|chunk| {
            let mut padded = [0u8; 4];
            padded[..chunk.len()].copy_from_slice(chunk);
            BabyBear::from_bytes(padded)
        })
        .collect();
    sponge(domain, bytes.len(), &elements)
}

/// The leaf hash STARK commitments use, built to be cheap to re-run in a
/// circuit: `elements` zero-padded to whole octets (8 elements), absorbed
/// by *overwriting* the rate, two octets per width-24 permutation (a final
/// lone octet overwrites only the rate's first half). The capacity starts
/// as `[domain, length, 0, ...]`, `length` being the caller's measure of
/// the input (its byte length, for `merkle`), so padding is unambiguous.
/// Overwriting means each permutation's input is whole octets of data plus
/// the previous permutation's output -- no in-circuit additions.
pub fn hash_octets(domain: u32, length: usize, elements: &[BabyBear]) -> [BabyBear; 8] {
    assert!(length < P as usize, "input too long to encode its length");
    let perm24 = perm24();
    let mut state = [BabyBear::ZERO; 24];
    state[SPONGE_RATE] = BabyBear::new(domain);
    state[SPONGE_RATE + 1] = BabyBear::new(length as u32);
    if elements.is_empty() {
        state = perm24.permute(state);
    }
    for block in elements.chunks(SPONGE_RATE) {
        let octets = block.len().div_ceil(8);
        state[..8 * octets].fill(BabyBear::ZERO);
        state[..block.len()].copy_from_slice(block);
        state = perm24.permute(state);
    }
    state[..8].try_into().unwrap()
}

/// Hash two digests into one -- a Merkle node -- in a single permutation
/// (their 16 elements fill the sponge's rate exactly).
/// `hash_octets` of `LANES` inputs of one length at once (lockstep
/// permutations: see `Poseidon2BabyBear::permute_lanes`).
pub fn hash_octets_lanes(domain: u32, length: usize, inputs: [&[BabyBear]; LANES]) -> [[BabyBear; 8]; LANES] {
    assert!(length < P as usize, "input too long to encode its length");
    let len = inputs[0].len();
    assert!(inputs.iter().all(|x| x.len() == len), "lanes must have equal lengths");
    let perm24 = perm24();
    let mut start = [BabyBear::ZERO; 24];
    start[SPONGE_RATE] = BabyBear::new(domain);
    start[SPONGE_RATE + 1] = BabyBear::new(length as u32);
    let mut states = [start; LANES];
    if len == 0 {
        states = perm24.permute_lanes(&states);
    }
    for offset in (0..len).step_by(SPONGE_RATE) {
        let block = SPONGE_RATE.min(len - offset);
        let octets = block.div_ceil(8);
        for (state, input) in states.iter_mut().zip(inputs) {
            state[..8 * octets].fill(BabyBear::ZERO);
            state[..block].copy_from_slice(&input[offset..offset + block]);
        }
        states = perm24.permute_lanes(&states);
    }
    states.map(|s| s[..8].try_into().unwrap())
}

/// `hash_pair` of `LANES` pairs at once.
pub fn hash_pair_lanes(domain: u32, pairs: [([BabyBear; 8], [BabyBear; 8]); LANES]) -> [[BabyBear; 8]; LANES] {
    let mut start = [BabyBear::ZERO; 24];
    start[SPONGE_RATE] = BabyBear::new(domain);
    start[SPONGE_RATE + 1] = BabyBear::new(16);
    let states = pairs.map(|(l, r)| {
        let mut s = start;
        s[..8].copy_from_slice(&l);
        s[8..16].copy_from_slice(&r);
        s
    });
    perm24().permute_lanes(&states).map(|s| s[..8].try_into().unwrap())
}

pub fn hash_pair(domain: u32, left: [BabyBear; 8], right: [BabyBear; 8]) -> [BabyBear; 8] {
    let mut elements = [BabyBear::ZERO; 16];
    elements[..8].copy_from_slice(&left);
    elements[8..].copy_from_slice(&right);
    sponge(domain, 16, &elements)
}

/// Eight field elements as 32 bytes (4 each, little-endian) -- how a
/// digest is stored and published.
pub fn digest_to_bytes(digest: [BabyBear; 8]) -> [u8; 32] {
    let mut out = [0u8; 32];
    for (i, elem) in digest.into_iter().enumerate() {
        out[i * 4..i * 4 + 4].copy_from_slice(&elem.to_bytes());
    }
    out
}

/// The inverse of `digest_to_bytes`. Each 4-byte group is reduced mod P,
/// so only bytes that came from a digest round-trip exactly.
pub fn digest_from_bytes(bytes: &[u8; 32]) -> [BabyBear; 8] {
    std::array::from_fn(|i| BabyBear::from_bytes(bytes[4 * i..4 * i + 4].try_into().unwrap()))
}

/// Hash arbitrary-length bytes down to a fixed 8-element digest: the
/// bytes packed 3 to an element (little-endian, the last zero-padded),
/// then `hash_elements`' sponge with the *byte* length recorded in the
/// capacity.
///
/// Three bytes, not four: 24 bits always fit below BabyBear's prime, so
/// the packing is one-to-one -- with four, different byte strings could
/// reduce to the same elements. And the byte length (not just the element
/// count) is what tells `"a"` apart from `"a\0"`, which pack identically.
pub fn hash_bytes(bytes: &[u8]) -> [BabyBear; 8] {
    let elements: Vec<BabyBear> = bytes
        .chunks(3)
        .map(|chunk| {
            let mut padded = [0u8; 4];
            padded[..chunk.len()].copy_from_slice(chunk);
            BabyBear::new(u32::from_le_bytes(padded))
        })
        .collect();
    sponge(DOMAIN_BYTES, bytes.len(), &elements)
}

/// `hash_bytes`, flattened to a plain 32-byte array (8 field elements, 4
/// bytes each, little-endian).
pub fn hash_bytes_32(bytes: &[u8]) -> [u8; 32] {
    let digest = hash_bytes(bytes);
    let mut out = [0u8; 32];
    for (i, elem) in digest.into_iter().enumerate() {
        out[i * 4..i * 4 + 4].copy_from_slice(&elem.to_bytes());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn elems(values: &[u32]) -> Vec<BabyBear> {
        values.iter().map(|&v| BabyBear::new(v)).collect()
    }

    /// Trailing zeros change the length, which is part of the hash -- the
    /// padding ambiguity `hash_bytes` has can't happen here.
    #[test]
    fn hash_elements_distinguishes_trailing_zeros() {
        let a = hash_elements(DOMAIN_COMMITMENT, &elems(&[1, 2]));
        let b = hash_elements(DOMAIN_COMMITMENT, &elems(&[1, 2, 0]));
        let c = hash_elements(DOMAIN_COMMITMENT, &elems(&[1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]));
        assert_ne!(a, b);
        assert_ne!(b, c);
        assert_ne!(hash_elements(DOMAIN_COMMITMENT, &[]), hash_elements(DOMAIN_COMMITMENT, &elems(&[0])));
    }

    #[test]
    fn hash_elements_separates_domains() {
        let input = elems(&[5, 6, 7]);
        assert_ne!(hash_elements(DOMAIN_COMMITMENT, &input), hash_elements(DOMAIN_SIGNING, &input));
    }

    /// The attack a capacity-less sponge allows: pick a second message
    /// whose later block cancels the first block's difference. Here the
    /// rate part is all an attacker can touch, so the "cancelling" block
    /// built for a zero-capacity sponge no longer works.
    #[test]
    fn hash_elements_resists_cancelling_a_block() {
        let perm = Poseidon2BabyBear::<24>::new();
        let first_a: Vec<BabyBear> = (0..16).map(BabyBear::new).collect();
        let first_b: Vec<BabyBear> = (100..116).map(BabyBear::new).collect();
        let second_a: Vec<BabyBear> = (200..216).map(BabyBear::new).collect();
        // Choose second_b so the full state after absorbing it would match
        // -- only possible in the rate part, so the capacity differs.
        let start = |first: &[BabyBear]| {
            let mut s = [BabyBear::ZERO; 24];
            s[16] = BabyBear::new(DOMAIN_COMMITMENT);
            s[17] = BabyBear::new(32);
            for (slot, &e) in s.iter_mut().zip(first) {
                *slot = *slot + e;
            }
            perm.permute(s)
        };
        let (sa, sb) = (start(&first_a), start(&first_b));
        assert_ne!(sa[16..], sb[16..], "the capacity must differ, or there'd be nothing to test");
        let second_b: Vec<BabyBear> = (0..16).map(|i| sa[i] + second_a[i] - sb[i]).collect();
        let a = hash_elements(DOMAIN_COMMITMENT, &[first_a, second_a].concat());
        let b = hash_elements(DOMAIN_COMMITMENT, &[first_b, second_b].concat());
        assert_ne!(a, b);
    }

    /// The padding and wrap-around ambiguities the old byte hash had.
    #[test]
    fn hash_bytes_distinguishes_padding_and_high_bytes() {
        assert_ne!(hash_bytes(b"ab"), hash_bytes(b"ab\0"));
        assert_ne!(hash_bytes(b"ab"), hash_bytes(b"ab\0\0\0\0"));
        assert_ne!(hash_bytes(b""), hash_bytes(b"\0"));
        // 0xffffffff would have reduced mod P under 4-byte packing.
        assert_ne!(hash_bytes(&[0xff; 4]), hash_bytes(&(0xffff_ffffu32 - P).to_le_bytes()));
    }

    #[test]
    fn hash_bytes_is_separated_from_hash_elements() {
        let bytes = [1u8, 0, 0];
        assert_ne!(hash_bytes(&bytes), hash_elements(DOMAIN_BYTES, &[BabyBear::ONE]));
    }

    #[test]
    fn digests_roundtrip_through_bytes() {
        let d = hash_elements(DOMAIN_SIGNING, &elems(&[9, 8, 7]));
        assert_eq!(digest_from_bytes(&digest_to_bytes(d)), d);
    }

    /// Plonky3's own known-answer test for `default_babybear_poseidon2_16`
    /// (baby-bear/src/poseidon2.rs, `test_default_babybear_poseidon2_width_16`).
    #[test]
    fn matches_plonky3_known_answer_width_16() {
        let input: [BabyBear; 16] = [
            894848333, 1437655012, 1200606629, 1690012884, 71131202, 1749206695, 1717947831,
            120589055, 19776022, 42382981, 1831865506, 724844064, 171220207, 1299207443, 227047920,
            1783754913,
        ]
        .map(BabyBear::new);

        let expected: [BabyBear; 16] = [
            516096821, 90309867, 1101817252, 1660784290, 360715097, 1789519026, 1788910906,
            563338433, 319524748, 1741414159, 1650859320, 894311162, 1121347488, 1692793758,
            1052633829, 1344246938,
        ]
        .map(BabyBear::new);

        assert_eq!(Poseidon2BabyBear::<16>::new().permute(input), expected);
    }

    /// Plonky3's known-answer test for `default_babybear_poseidon2_24`
    /// (`test_default_babybear_poseidon2_width_24`).
    #[test]
    fn matches_plonky3_known_answer_width_24() {
        let input: [BabyBear; 24] = [
            886409618, 1327899896, 1902407911, 591953491, 648428576, 1844789031, 1198336108,
            355597330, 1799586834, 59617783, 790334801, 1968791836, 559272107, 31054313,
            1042221543, 474748436, 135686258, 263665994, 1962340735, 1741539604, 2026927696,
            449439011, 1131357108, 50869465,
        ]
        .map(BabyBear::new);

        let expected: [BabyBear; 24] = [
            882297297, 1264077610, 512812497, 782602970, 867738552, 1251075457, 309180082,
            340784773, 524041877, 351272188, 404451680, 15001466, 322926653, 1773004150,
            1718440818, 674682955, 1154713225, 1719133502, 324232301, 1005243141, 443371079,
            268735940, 770060019, 718377682,
        ]
        .map(BabyBear::new);

        assert_eq!(Poseidon2BabyBear::<24>::new().permute(input), expected);
    }

    /// Plonky3's known-answer test for `default_babybear_poseidon2_32`
    /// (`test_default_babybear_poseidon2_width_32`).
    #[test]
    fn matches_plonky3_known_answer_width_32() {
        let input: [BabyBear; 32] = [
            377682961, 1957793603, 980981814, 6565119, 1583211709, 176593168, 1672635515,
            226854190, 1096634172, 1317773742, 1472230830, 1621534427, 559807320, 1484241910,
            1847825942, 3491998, 950152427, 1935451636, 275759400, 227625951, 1271142011,
            1492341973, 1502961189, 147694103, 1939834518, 1449972249, 1822424048, 1518111482,
            714203295, 383863563, 411489861, 1253612091,
        ]
        .map(BabyBear::new);

        let expected: [BabyBear; 32] = [
            303440672, 985419733, 780962554, 1395263823, 188752116, 1348917749, 677984158,
            667170017, 97281439, 178741618, 1770541242, 1894441262, 847173187, 1374453653,
            1242356754, 1485142795, 1019698843, 334329175, 540395852, 918117757, 1288401072,
            508687761, 996827321, 1660764537, 546969284, 1848510002, 334793951, 736596659,
            1928951999, 1444080616, 55017699, 1832626373,
        ]
        .map(BabyBear::new);

        assert_eq!(Poseidon2BabyBear::<32>::new().permute(input), expected);
    }

    #[test]
    fn sbox_is_bijective() {
        assert_ne!((P - 1) % 7, 0);
    }

    #[test]
    fn hash_is_deterministic_and_sensitive() {
        let p2 = Poseidon2BabyBear16::new();
        let a = [BabyBear::new(1), BabyBear::new(2), BabyBear::new(3)];
        let b = [BabyBear::new(1), BabyBear::new(2), BabyBear::new(4)];
        assert_eq!(p2.hash(&a), p2.hash(&a));
        assert_ne!(p2.hash(&a), p2.hash(&b));
    }

    #[test]
    fn sub_is_inverse_of_add() {
        let a = BabyBear::new(12345);
        let b = BabyBear::new(67890);
        assert_eq!(a.add(b).sub(b), a);
        assert_eq!(a.sub(a), BabyBear::ZERO);
        // b > 0, so a.sub(a) above never reaches neg()'s self.0 == 0 branch;
        // subtracting ZERO does, via ZERO.neg().
        assert_eq!(a.sub(BabyBear::ZERO), a);
    }

    /// Not a correctness test: single-thread permutation speed. Run with
    /// `cargo test --release -- --ignored --nocapture permutation_speed`.
    #[test]
    #[ignore]
    fn permutation_speed() {
        let perm = perm24();
        let mut state = [BabyBear::new(1); 24];
        let n = 200_000;
        let start = std::time::Instant::now();
        for _ in 0..n {
            state = perm.permute(state);
        }
        let per = start.elapsed().as_nanos() as f64 / n as f64;
        println!("width-24 permutation: {per:.0} ns ({:?})", state[0]);
        let perm16 = perm16();
        let mut state = [BabyBear::new(1); 16];
        let start = std::time::Instant::now();
        for _ in 0..n {
            state = perm16.permute(state);
        }
        let per = start.elapsed().as_nanos() as f64 / n as f64;
        println!("width-16 permutation: {per:.0} ns ({:?})", state[0]);
        let mut states = [[BabyBear::new(1); 24]; LANES];
        let start = std::time::Instant::now();
        for _ in 0..n / LANES {
            states = perm.permute_lanes(&states);
        }
        let per = start.elapsed().as_nanos() as f64 / n as f64;
        println!("width-24, {LANES} in lockstep: {per:.0} ns per permutation ({:?})", states[0][0]);
    }


    #[test]
    fn the_fast_permutation_matches_the_reference() {
        let mut state24 = [BabyBear::ZERO; 24];
        let mut state16 = [BabyBear::ZERO; 16];
        for round in 0..50u32 {
            for (i, x) in state24.iter_mut().enumerate() {
                *x = *x + BabyBear::new(round.wrapping_mul(2_654_435_761).wrapping_add(i as u32 * 97));
            }
            for (i, x) in state16.iter_mut().enumerate() {
                *x = *x + BabyBear::new(round.wrapping_mul(40_503).wrapping_add(i as u32));
            }
            assert_eq!(perm24().permute(state24), perm24().permute_reference(state24));
            assert_eq!(perm16().permute(state16), perm16().permute_reference(state16));
            state24 = perm24().permute(state24);
            state16 = perm16().permute(state16);
        }
        // Lockstep lanes agree with one at a time.
        let lanes: [[BabyBear; 24]; LANES] =
            std::array::from_fn(|l| std::array::from_fn(|i| BabyBear::new(((l * 1000 + i * 7919) as u32).wrapping_mul(31337))));
        let together = perm24().permute_lanes(&lanes);
        for l in 0..LANES {
            assert_eq!(together[l], perm24().permute(lanes[l]));
        }
        // Extremes: all zero, all P - 1.
        let top = BabyBear::new(P - 1);
        assert_eq!(perm24().permute([top; 24]), perm24().permute_reference([top; 24]));
        assert_eq!(perm24().permute([BabyBear::ZERO; 24]), perm24().permute_reference([BabyBear::ZERO; 24]));
    }


    #[test]
    fn wide_reduction_matches_modulo() {
        let p = P as u64;
        for x in [0, 1, p - 1, p, p + 1, 2 * p, (1 << 37) - 1, 49 * p - 1, 24 * (p - 1), 1 << 31, (1 << 34) + 12345] {
            assert_eq!(reduce_wide(x) as u64, x % p, "{x}");
        }
        let mut x: u64 = 0x1234_5678;
        for _ in 0..100_000 {
            x = x.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            let v = x >> 27; // < 2^37
            assert_eq!(reduce_wide(v) as u64, v % p);
        }
    }


    /// The portable path (what CPUs without AVX2, or other
    /// architectures, run) agrees with whatever `permute_lanes` picked.
    #[test]
    fn portable_lanes_match_the_dispatched_ones() {
        let lanes: [[BabyBear; 24]; LANES] =
            std::array::from_fn(|l| std::array::from_fn(|i| BabyBear::new(((l * 31 + i) as u32).wrapping_mul(2_654_435_761))));
        assert_eq!(perm24().permute_lanes_generic(&lanes), perm24().permute_lanes(&lanes));
    }

}

