//! Poseidon2 over the BabyBear field, generic over state width.
//!
//! Three widths are implemented: t=16 (the standard/default BabyBear
//! instantiation used by Plonky3 and SP1), and t=24 / t=32 (wider sponge
//! configurations Plonky3 also publishes). t=4 is *not* a published
//! configuration for this field.
//!
//! All constants below -- external/internal round constants, the internal
//! diagonal, and the 4x4 MDS matrix used by the external linear layer -- are
//! copied from Plonky3's `baby-bear/src/poseidon2.rs`
//! (https://github.com/Plonky3/Plonky3), itself generated by the official
//! Grain-LFSR constant generator per the Poseidon2 paper
//! (https://eprint.iacr.org/2023/323).
//!
//! Correctness for all three widths is checked against Plonky3's own
//! known-answer test vectors in the `tests` module below.
//!
//! `main.rs` doesn't currently call into this module's public API (it just
//! prints "Hello world!"), so allow dead code here rather than suppressing
//! warnings piecemeal -- this module exists to be exercised by its tests.
#![allow(dead_code)]

/// The BabyBear prime: 2^31 - 2^27 + 1.
pub const P: u32 = 2_013_265_921;

const HALF_FULL_ROUNDS: usize = 4; // R_F = 8 total (4 initial + 4 final), same for every width here.

/// An element of the BabyBear field, always kept reduced into [0, P).
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub struct BabyBear(u32);

impl BabyBear {
    pub const ZERO: BabyBear = BabyBear(0);
    pub const ONE: BabyBear = BabyBear(1);

    pub fn new(x: u32) -> Self {
        BabyBear(x % P)
    }

    pub fn value(self) -> u32 {
        self.0
    }

    pub fn neg(self) -> Self {
        if self.0 == 0 {
            self
        } else {
            BabyBear(P - self.0)
        }
    }

    pub fn add(self, rhs: Self) -> Self {
        let sum = self.0 + rhs.0;
        BabyBear(if sum >= P { sum - P } else { sum })
    }

    pub fn sub(self, rhs: Self) -> Self {
        self.add(rhs.neg())
    }

    pub fn mul(self, rhs: Self) -> Self {
        BabyBear(((self.0 as u64 * rhs.0 as u64) % P as u64) as u32)
    }

    pub fn double(self) -> Self {
        self.add(self)
    }

    /// Exponentiation by repeated squaring.
    pub fn pow(self, mut exp: u64) -> Self {
        let mut base = self;
        let mut acc = BabyBear::ONE;
        while exp > 0 {
            if exp & 1 == 1 {
                acc = acc.mul(base);
            }
            base = base.mul(base);
            exp >>= 1;
        }
        acc
    }

    /// Multiplicative inverse via Fermat's little theorem (a^(P-2) = a^-1).
    pub fn inverse(self) -> Self {
        self.pow((P - 2) as u64)
    }

    /// The Poseidon2 S-box for BabyBear: x -> x^7. (gcd(7, P-1) = 1, so this is
    /// a bijection; degree 3 and 5 are *not* valid here since both divide P-1.)
    fn sbox(self) -> Self {
        let x2 = self.mul(self);
        let x4 = x2.mul(x2);
        x4.mul(x2).mul(self)
    }
}

impl std::ops::Add for BabyBear {
    type Output = BabyBear;
    fn add(self, rhs: Self) -> Self {
        BabyBear::add(self, rhs)
    }
}

impl std::ops::Mul for BabyBear {
    type Output = BabyBear;
    fn mul(self, rhs: Self) -> Self {
        BabyBear::mul(self, rhs)
    }
}

/// 1 / 2^k, computed via the field inverse rather than a pasted constant.
fn inv_two_pow(k: u32) -> BabyBear {
    BabyBear::new(1 << k).inverse()
}

// --- Round constants, verbatim from Plonky3's baby-bear/src/poseidon2.rs ---

const EXTERNAL_RC_INITIAL_16: [[u32; 16]; HALF_FULL_ROUNDS] = [
    [
        1774958255, 1185780729, 1621102414, 1796380621, 588815102, 1932426223, 1925334750,
        747903232, 89648862, 360728943, 977184635, 1425273457, 256487465, 1200041953, 572403254,
        448208942,
    ],
    [
        1215789478, 944884184, 953948096, 547326025, 646827752, 889997530, 1536873262, 86189867,
        1065944411, 32019634, 333311454, 456061748, 1963448500, 1827584334, 1391160226, 1348741381,
    ],
    [
        88424255, 104111868, 1763866748, 79691676, 1988915530, 1050669594, 359890076, 573163527,
        222820492, 159256268, 669703072, 763177444, 889367200, 256335831, 704371273, 25886717,
    ],
    [
        51754520, 1833211857, 454499742, 1384520381, 777848065, 1053320300, 1851729162, 344647910,
        401996362, 1046925956, 5351995, 1212119315, 754867989, 36972490, 751272725, 506915399,
    ],
];

const EXTERNAL_RC_FINAL_16: [[u32; 16]; HALF_FULL_ROUNDS] = [
    [
        1922082829, 1870549801, 1502529704, 1990744480, 1700391016, 1702593455, 321330495,
        528965731, 183414327, 1886297254, 1178602734, 1923111974, 744004766, 549271463, 1781349648,
        542259047,
    ],
    [
        1536158148, 715456982, 503426110, 340311124, 1558555932, 1226350925, 742828095, 1338992758,
        1641600456, 1843351545, 301835475, 43203215, 386838401, 1520185679, 1235297680, 904680097,
    ],
    [
        1491801617, 1581784677, 913384905, 247083962, 532844013, 107190701, 213827818, 1979521776,
        1358282574, 1681743681, 1867507480, 1530706910, 507181886, 695185447, 1172395131,
        1250800299,
    ],
    [
        1503161625, 817684387, 498481458, 494676004, 1404253825, 108246855, 59414691, 744214112,
        890862029, 1342765939, 1417398904, 1897591937, 1066647396, 1682806907, 1015795079,
        1619482808,
    ],
];

const INTERNAL_RC_16: [u32; 13] = [
    1518359488, 1765533241, 945325693, 422793067, 311365592, 1311448267, 1629555936, 1009879353,
    190525218, 786108885, 557776863, 212616710, 605745517,
];

const EXTERNAL_RC_INITIAL_24: [[u32; 24]; HALF_FULL_ROUNDS] = [
    [
        262278199, 127253399, 314968988, 246143118, 157582794, 118043943, 454905424, 815798990,
        1004040026, 1773108264, 1066694495, 1930780904, 1180307149, 1464793095, 1660766320,
        1389166148, 343354132, 1307439985, 638242172, 525458520, 1964135730, 1751797115,
        1421525369, 831813382,
    ],
    [
        695835963, 1845603984, 540703332, 1333667262, 1917861751, 1170029417, 1989924532,
        1518763784, 1339793538, 622609176, 686842369, 1737016378, 1282239129, 897025192, 716894289,
        1997503974, 395622276, 1201063290, 1917549072, 1150912935, 1687379185, 1507936940,
        241306552, 989176635,
    ],
    [
        1147522062, 27129487, 1257820264, 142102402, 217046702, 1664590951, 855276054, 1215259350,
        946500736, 552696906, 1424297384, 538103555, 1608853840, 162510541, 623051854, 1549062383,
        1908416316, 1622328571, 1079030649, 1584033957, 1099252725, 1910423126, 447555988,
        862495875,
    ],
    [
        128479034, 1587822577, 608401422, 1290028279, 342857858, 825405577, 427731030, 1718628547,
        588764636, 204228775, 1454563174, 1740472809, 1338899225, 1269493554, 53007114, 1647670797,
        306391314, 172614232, 51256176, 1221257987, 1239734761, 273790406, 1781980094, 1291790245,
    ],
];

const EXTERNAL_RC_FINAL_24: [[u32; 24]; HALF_FULL_ROUNDS] = [
    [
        53041581, 723038058, 1439947916, 1136469704, 205609311, 1883820770, 14387587, 720724951,
        1854174607, 1629316321, 530151394, 1679178250, 1549779579, 48375137, 976057819, 463976218,
        875839332, 1946596189, 434078361, 1878280202, 1363837384, 1470845646, 1792450386,
        1040977421,
    ],
    [
        1209164052, 714957516, 390340387, 1213686459, 790726260, 117294666, 140621810, 993455846,
        1889603648, 78845751, 925018226, 708123747, 1647665372, 1649953458, 942439428, 1006235079,
        238616145, 930036496, 1401020792, 989618631, 1545325389, 1715719711, 755691969, 150307788,
    ],
    [
        1567618575, 1663353317, 1950429111, 1891637550, 192082241, 1080533265, 1463323727,
        890243564, 158646617, 1402624179, 59510015, 1198261138, 1065075039, 1150410028, 1293938517,
        76770019, 1478577620, 1748789933, 457372011, 1841795381, 760115692, 1042892522, 1507649755,
        1827572010,
    ],
    [
        1206940496, 1896271507, 1003792297, 738091882, 1124078057, 1889898, 813674331, 228520958,
        1832911930, 781141772, 459826664, 202271745, 1296144415, 1111203133, 1090783436, 641665156,
        1393671120, 1303271640, 809508074, 162506101, 1262312258, 1672219447, 1608891156,
        1380248020,
    ],
];

const INTERNAL_RC_24: [u32; 21] = [
    497520322, 1930103076, 1052077299, 1540960371, 924863639, 1365519753, 1726563304, 440300254,
    1891545577, 822033215, 1111544260, 308575117, 1708681573, 1240419708, 1199068823, 1186174623,
    1551596046, 1886977120, 1327682690, 1210751726, 1810596765,
];

const EXTERNAL_RC_INITIAL_32: [[u32; 32]; HALF_FULL_ROUNDS] = [
    [
        1729160065, 27999661, 1237173535, 1103727717, 596139402, 619347324, 1801845869, 1627808090,
        139024371, 360461876, 1303224591, 1826595949, 468846782, 1540501420, 1284230111, 670536848,
        1883853842, 708936782, 1371236849, 840293409, 1729185817, 665479689, 1598897325,
        1607911204, 457969805, 1469698125, 1452024111, 1745363419, 1644640041, 580839296,
        995071171, 396602452,
    ],
    [
        1815642745, 1215757909, 829485578, 862993998, 60295857, 19902714, 341764315, 1233214256,
        1185777564, 1388073021, 1483026647, 1547106789, 42886403, 137429864, 1968465478,
        1931810545, 860372570, 77628460, 439432665, 1400581809, 1538215799, 1266208109, 1525492810,
        1724421089, 1012175782, 1187392508, 1447975194, 1390335911, 13697837, 724621313, 270380023,
        788210125,
    ],
    [
        1245060153, 1240462706, 773049076, 24012697, 459070276, 399125958, 240127712, 21088923,
        664478582, 1715979275, 231403068, 384302329, 1508300380, 515322057, 677410888, 1165131676,
        1314144251, 65938768, 17618251, 47991670, 725260860, 783004377, 110265683, 757314549,
        1839407793, 354937863, 239405946, 1402344978, 552692496, 384830560, 1278858511, 1104518518,
    ],
    [
        1381234722, 995349377, 461326090, 1581091164, 1382383909, 18976979, 1700150144, 487565895,
        896906185, 1275960608, 416280735, 1688722012, 789842725, 329227825, 1726180309, 1682098193,
        1485282254, 1607239622, 1745333772, 1091683927, 1664911657, 1955998065, 1069649592,
        1164767880, 838256850, 1815753128, 1837293392, 1027811219, 1100325527, 1808702357,
        1015163632, 1982457267,
    ],
];

const EXTERNAL_RC_FINAL_32: [[u32; 32]; HALF_FULL_ROUNDS] = [
    [
        2009876055, 956324903, 1221427337, 645725371, 474073733, 1102287935, 552039034, 1689090291,
        333267987, 272819164, 1957554988, 768463815, 100691900, 900073961, 229582652, 978282831,
        1509756957, 668078379, 423081631, 780697788, 1086399529, 108619174, 1856090989, 1845577582,
        701329802, 1409730195, 1373515418, 1843148938, 1400255603, 396516543, 522814157, 432691965,
    ],
    [
        762330259, 203964644, 752517837, 1551847904, 498436102, 1018571729, 725960219, 1644477008,
        1750593724, 1257415528, 851527412, 449830291, 767792496, 230550350, 1354692685, 1870897708,
        1129068353, 543220064, 1760923403, 623489725, 288114536, 1883282658, 458704398, 568099212,
        1600869168, 1145016250, 555389150, 1495091760, 1532640885, 1666986810, 519924336,
        1563771999,
    ],
    [
        1446498082, 1855695025, 280317484, 69803704, 760128835, 1913281633, 442196771, 1759606503,
        638883701, 1492323307, 1157890731, 613581397, 851810645, 727413345, 1652127647, 1503357582,
        1892763091, 931579089, 288765024, 587145601, 1292303440, 665363423, 1685977476, 980716739,
        1252597410, 569037473, 1355636109, 114753478, 1539641623, 1173899452, 314824177,
        1216319589,
    ],
    [
        370615356, 1552381156, 1992086508, 882674251, 643656246, 972842286, 610808232, 1216370940,
        173831638, 1980583661, 757684141, 1636349694, 545572213, 1741029216, 1030588827, 660162122,
        507714002, 167704630, 810967268, 607642520, 1770949549, 1369555082, 1869300458, 1316643372,
        861517941, 1875492637, 882822549, 1076559853, 243081034, 1969815445, 1831269979,
        1383829493,
    ],
];

const INTERNAL_RC_32: [u32; 30] = [
    1037946958, 1513948504, 1983802485, 1735335304, 2008556117, 635406929, 1769749264, 63925983,
    313872248, 1714672948, 1114619063, 1430676956, 1451867570, 317147102, 1623361349, 298470309,
    1057985923, 1455937939, 553027423, 1776654280, 1016141171, 700970754, 442032405, 688992664,
    2003511455, 512896738, 560331760, 684502904, 428025981, 1227563744,
];

/// Internal-layer diagonal for width 16: M_I = J + diag(V) (J = all-ones
/// matrix). Expressed via field inverses rather than pasted decimal
/// constants, so the arithmetic is checkable by inspection, and transcribed
/// directly from Plonky3's `InternalLayerBaseParameters<_, 16>::internal_layer_mat_mul`.
fn diagonal_16() -> [BabyBear; 16] {
    let (two, three, four) = (BabyBear::new(2), BabyBear::new(3), BabyBear::new(4));
    let inv2 = two.inverse();
    [
        two.neg(),
        BabyBear::ONE,
        two,
        inv2,
        three,
        four,
        inv2.neg(),
        three.neg(),
        four.neg(),
        inv_two_pow(8),
        inv_two_pow(2),
        inv_two_pow(3),
        inv_two_pow(27),
        inv_two_pow(8).neg(),
        inv_two_pow(4).neg(),
        inv_two_pow(27).neg(),
    ]
}

/// Internal-layer diagonal for width 24, transcribed the same way from
/// `InternalLayerBaseParameters<_, 24>::internal_layer_mat_mul`.
fn diagonal_24() -> [BabyBear; 24] {
    let (two, three, four) = (BabyBear::new(2), BabyBear::new(3), BabyBear::new(4));
    let inv2 = two.inverse();
    [
        two.neg(),
        BabyBear::ONE,
        two,
        inv2,
        three,
        four,
        inv2.neg(),
        three.neg(),
        four.neg(),
        inv_two_pow(8),
        inv_two_pow(2),
        inv_two_pow(3),
        inv_two_pow(4),
        inv_two_pow(7),
        inv_two_pow(9),
        inv_two_pow(27),
        inv_two_pow(8).neg(),
        inv_two_pow(2).neg(),
        inv_two_pow(3).neg(),
        inv_two_pow(4).neg(),
        inv_two_pow(5).neg(),
        inv_two_pow(6).neg(),
        inv_two_pow(7).neg(),
        inv_two_pow(27).neg(),
    ]
}

/// Internal-layer diagonal for width 32, transcribed the same way from
/// `InternalLayerBaseParameters<_, 32>::internal_layer_mat_mul`.
fn diagonal_32() -> [BabyBear; 32] {
    let (two, three, four) = (BabyBear::new(2), BabyBear::new(3), BabyBear::new(4));
    let inv2 = two.inverse();
    [
        two.neg(),
        BabyBear::ONE,
        two,
        inv2,
        three,
        four,
        inv2.neg(),
        three.neg(),
        four.neg(),
        inv_two_pow(8),
        inv_two_pow(2),
        inv_two_pow(3),
        inv_two_pow(4),
        inv_two_pow(5),
        inv_two_pow(6),
        inv_two_pow(7),
        inv_two_pow(9),
        inv_two_pow(10),
        inv_two_pow(12),
        inv_two_pow(27),
        inv_two_pow(8).neg(),
        inv_two_pow(2).neg(),
        inv_two_pow(3).neg(),
        inv_two_pow(4).neg(),
        inv_two_pow(5).neg(),
        inv_two_pow(6).neg(),
        inv_two_pow(7).neg(),
        inv_two_pow(9).neg(),
        inv_two_pow(10).neg(),
        inv_two_pow(12).neg(),
        inv_two_pow(14).neg(),
        inv_two_pow(27).neg(),
    ]
}

/// The fastest 4x4 MDS matrix from the Poseidon2 paper (Appendix B), used as
/// the building block of every external linear layer here:
///   [ 2 3 1 1 ]
///   [ 1 2 3 1 ]
///   [ 1 1 2 3 ]
///   [ 3 1 1 2 ]
fn apply_mat4(x: &mut [BabyBear; 4]) {
    let t01 = x[0] + x[1];
    let t23 = x[2] + x[3];
    let t0123 = t01 + t23;
    let t01123 = t0123 + x[1];
    let t01233 = t0123 + x[3];
    x[3] = t01233 + x[0].double();
    x[1] = t01123 + x[2].double();
    x[0] = t01123 + t01;
    x[2] = t01233 + t23;
}

/// The external linear layer: apply the 4x4 MDS matrix to each 4-element
/// chunk of the state, then mix across chunks at each position. Equivalent
/// to multiplying by the `WIDTH x WIDTH` block matrix
/// `[[2M M ... M], [M 2M ... M], ..., [M M ... 2M]]` for the 4x4 matrix M above.
/// Works for any WIDTH that's a multiple of 4.
fn apply_external_layer<const WIDTH: usize>(state: &mut [BabyBear; WIDTH]) {
    for chunk in state.chunks_mut(4) {
        let mut block: [BabyBear; 4] = chunk.try_into().unwrap();
        apply_mat4(&mut block);
        chunk.copy_from_slice(&block);
    }

    let mut sums = [BabyBear::ZERO; 4];
    for k in 0..4 {
        for j in (0..WIDTH).step_by(4) {
            sums[k] = sums[k] + state[j + k];
        }
    }
    for (i, elem) in state.iter_mut().enumerate() {
        *elem = *elem + sums[i % 4];
    }
}

/// The internal (partial-round) linear layer: (J + diag(V)) * state, i.e.
/// out[i] = V[i] * state[i] + sum(state).
fn apply_internal_layer<const WIDTH: usize>(
    state: &mut [BabyBear; WIDTH],
    diag: &[BabyBear; WIDTH],
) {
    let sum = state.iter().fold(BabyBear::ZERO, |a, &b| a + b);
    for i in 0..WIDTH {
        state[i] = state[i] * diag[i] + sum;
    }
}

/// A Poseidon2 permutation over BabyBear at a given state width.
pub struct Poseidon2BabyBear<const WIDTH: usize> {
    ext_initial: [[BabyBear; WIDTH]; HALF_FULL_ROUNDS],
    ext_final: [[BabyBear; WIDTH]; HALF_FULL_ROUNDS],
    internal_rc: Vec<BabyBear>,
    internal_diag: [BabyBear; WIDTH],
}

impl<const WIDTH: usize> Poseidon2BabyBear<WIDTH> {
    /// The full Poseidon2 permutation: an initial external linear layer, then
    /// R_F/2 full rounds, R_P partial rounds, and R_F/2 more full rounds.
    pub fn permute(&self, input: [BabyBear; WIDTH]) -> [BabyBear; WIDTH] {
        let mut s = input;
        apply_external_layer(&mut s);

        for round in &self.ext_initial {
            for i in 0..WIDTH {
                s[i] = (s[i] + round[i]).sbox();
            }
            apply_external_layer(&mut s);
        }

        for &rc in &self.internal_rc {
            s[0] = (s[0] + rc).sbox();
            apply_internal_layer(&mut s, &self.internal_diag);
        }

        for round in &self.ext_final {
            for i in 0..WIDTH {
                s[i] = (s[i] + round[i]).sbox();
            }
            apply_external_layer(&mut s);
        }

        s
    }

    /// A simple sponge on top of the verified permutation: absorb up to
    /// `WIDTH` field elements (zero-padded) with capacity fixed to zero, and
    /// return the first 8 output limbs as the digest. This is a
    /// straightforward construction built on the permutation above, not a
    /// copy of any particular Plonky3 hasher's rate/capacity wiring.
    pub fn hash(&self, inputs: &[BabyBear]) -> [BabyBear; 8] {
        assert!(
            inputs.len() <= WIDTH,
            "input longer than one absorption (width {WIDTH})"
        );
        let mut state = [BabyBear::ZERO; WIDTH];
        state[..inputs.len()].copy_from_slice(inputs);
        let out = self.permute(state);
        out[..8].try_into().unwrap()
    }

    /// `PoseidonCompress_{WIDTH,U}(x) = Truncate_U(permute(x) + x)`: a
    /// Miyaguchi-Preneel-style feed-forward compression function, following
    /// the notation and construction in Drake, "Technical Note: LeanSig for
    /// Post-Quantum Ethereum" (IACR eprint 2025/1332), Section 5. This is the
    /// hash-call shape that scheme uses throughout a Poseidon2-based WOTS
    /// (chain hashing, message hashing, etc.) rather than the bare
    /// permutation or the sponge above.
    pub fn compress<const U: usize>(&self, input: [BabyBear; WIDTH]) -> [BabyBear; U] {
        debug_assert!(U <= WIDTH, "compress output width must fit the state");
        let permuted = self.permute(input);
        let mut out = [BabyBear::ZERO; U];
        for (i, slot) in out.iter_mut().enumerate() {
            *slot = permuted[i] + input[i];
        }
        out
    }
}

impl Poseidon2BabyBear<16> {
    pub fn new() -> Self {
        Poseidon2BabyBear {
            ext_initial: EXTERNAL_RC_INITIAL_16.map(|r| r.map(BabyBear::new)),
            ext_final: EXTERNAL_RC_FINAL_16.map(|r| r.map(BabyBear::new)),
            internal_rc: INTERNAL_RC_16.map(BabyBear::new).to_vec(),
            internal_diag: diagonal_16(),
        }
    }
}

impl Poseidon2BabyBear<24> {
    pub fn new() -> Self {
        Poseidon2BabyBear {
            ext_initial: EXTERNAL_RC_INITIAL_24.map(|r| r.map(BabyBear::new)),
            ext_final: EXTERNAL_RC_FINAL_24.map(|r| r.map(BabyBear::new)),
            internal_rc: INTERNAL_RC_24.map(BabyBear::new).to_vec(),
            internal_diag: diagonal_24(),
        }
    }
}

impl Poseidon2BabyBear<32> {
    pub fn new() -> Self {
        Poseidon2BabyBear {
            ext_initial: EXTERNAL_RC_INITIAL_32.map(|r| r.map(BabyBear::new)),
            ext_final: EXTERNAL_RC_FINAL_32.map(|r| r.map(BabyBear::new)),
            internal_rc: INTERNAL_RC_32.map(BabyBear::new).to_vec(),
            internal_diag: diagonal_32(),
        }
    }
}

/// t = 16 is the standard BabyBear instantiation (Plonky3/SP1's default).
pub type Poseidon2BabyBear16 = Poseidon2BabyBear<16>;

#[cfg(test)]
mod tests {
    use super::*;

    /// Plonky3's own known-answer test for `default_babybear_poseidon2_16`
    /// (baby-bear/src/poseidon2.rs, `test_default_babybear_poseidon2_width_16`).
    #[test]
    fn matches_plonky3_known_answer_width_16() {
        let input: [BabyBear; 16] = [
            894848333, 1437655012, 1200606629, 1690012884, 71131202, 1749206695, 1717947831,
            120589055, 19776022, 42382981, 1831865506, 724844064, 171220207, 1299207443, 227047920,
            1783754913,
        ]
        .map(BabyBear::new);

        let expected: [BabyBear; 16] = [
            516096821, 90309867, 1101817252, 1660784290, 360715097, 1789519026, 1788910906,
            563338433, 319524748, 1741414159, 1650859320, 894311162, 1121347488, 1692793758,
            1052633829, 1344246938,
        ]
        .map(BabyBear::new);

        assert_eq!(Poseidon2BabyBear::<16>::new().permute(input), expected);
    }

    /// Plonky3's known-answer test for `default_babybear_poseidon2_24`
    /// (`test_default_babybear_poseidon2_width_24`).
    #[test]
    fn matches_plonky3_known_answer_width_24() {
        let input: [BabyBear; 24] = [
            886409618, 1327899896, 1902407911, 591953491, 648428576, 1844789031, 1198336108,
            355597330, 1799586834, 59617783, 790334801, 1968791836, 559272107, 31054313,
            1042221543, 474748436, 135686258, 263665994, 1962340735, 1741539604, 2026927696,
            449439011, 1131357108, 50869465,
        ]
        .map(BabyBear::new);

        let expected: [BabyBear; 24] = [
            882297297, 1264077610, 512812497, 782602970, 867738552, 1251075457, 309180082,
            340784773, 524041877, 351272188, 404451680, 15001466, 322926653, 1773004150,
            1718440818, 674682955, 1154713225, 1719133502, 324232301, 1005243141, 443371079,
            268735940, 770060019, 718377682,
        ]
        .map(BabyBear::new);

        assert_eq!(Poseidon2BabyBear::<24>::new().permute(input), expected);
    }

    /// Plonky3's known-answer test for `default_babybear_poseidon2_32`
    /// (`test_default_babybear_poseidon2_width_32`).
    #[test]
    fn matches_plonky3_known_answer_width_32() {
        let input: [BabyBear; 32] = [
            377682961, 1957793603, 980981814, 6565119, 1583211709, 176593168, 1672635515,
            226854190, 1096634172, 1317773742, 1472230830, 1621534427, 559807320, 1484241910,
            1847825942, 3491998, 950152427, 1935451636, 275759400, 227625951, 1271142011,
            1492341973, 1502961189, 147694103, 1939834518, 1449972249, 1822424048, 1518111482,
            714203295, 383863563, 411489861, 1253612091,
        ]
        .map(BabyBear::new);

        let expected: [BabyBear; 32] = [
            303440672, 985419733, 780962554, 1395263823, 188752116, 1348917749, 677984158,
            667170017, 97281439, 178741618, 1770541242, 1894441262, 847173187, 1374453653,
            1242356754, 1485142795, 1019698843, 334329175, 540395852, 918117757, 1288401072,
            508687761, 996827321, 1660764537, 546969284, 1848510002, 334793951, 736596659,
            1928951999, 1444080616, 55017699, 1832626373,
        ]
        .map(BabyBear::new);

        assert_eq!(Poseidon2BabyBear::<32>::new().permute(input), expected);
    }

    #[test]
    fn sbox_is_bijective() {
        assert_ne!((P - 1) % 7, 0);
    }

    #[test]
    fn hash_is_deterministic_and_sensitive() {
        let p2 = Poseidon2BabyBear16::new();
        let a = [BabyBear::new(1), BabyBear::new(2), BabyBear::new(3)];
        let b = [BabyBear::new(1), BabyBear::new(2), BabyBear::new(4)];
        assert_eq!(p2.hash(&a), p2.hash(&a));
        assert_ne!(p2.hash(&a), p2.hash(&b));
    }

    #[test]
    fn sub_is_inverse_of_add() {
        let a = BabyBear::new(12345);
        let b = BabyBear::new(67890);
        assert_eq!(a.add(b).sub(b), a);
        assert_eq!(a.sub(a), BabyBear::ZERO);
        // b > 0, so a.sub(a) above never reaches neg()'s self.0 == 0 branch;
        // subtracting ZERO does, via ZERO.neg().
        assert_eq!(a.sub(BabyBear::ZERO), a);
    }
}
